Database-based storage
mindsdb/mindsdb pull request #1013
Opened 2020-12-16 14:41 UTC by George3d6

## Why
* We need a centralized state containing datasources, configs and predicotrs that can be used by multiple mindsdb
* We need this centralized state to be easy to synchronize

## How
* In short, by moving the "logic" data layer of mindsdb to a sqlalchemy based ORM

## Extra
* Removed installer code
* Removed a bunch of already dead code
* Removed code that was no longer necessary

2021-01-10 11:22 UTC, George3d6 commented
All tests pass successfully locally but for some reason still fail when ran remotely

2021-01-11 13:36 UTC, StpMax requested changes

2021-01-11 13:36 UTC, StpMax commented on .gitignore
> +mindsdb.sqlite.db
double lines

2021-01-11 13:36 UTC, StpMax commented on mindsdb/__init__.py
> +        db_config = json.loads(fp)
is no `import json` above

2021-01-11 13:37 UTC, StpMax commented
need change `error` to `info` here https://github.com/mindsdb/mindsdb/blob/01a9ceeaacabc92022e990b37a8233022c5bf1d6/mindsdb/api/http/initialize.py#L231

2021-01-11 13:43 UTC, StpMax commented
`GET datasources/` returns x5 copies of every DS. I upload one `hr1`, then `GET datasources/` return to me:
![image](https://user-images.githubusercontent.com/4068133/104189708-f1ee4180-5412-11eb-8fc3-4e95b20fa782.png)

2021-01-11 13:44 UTC, StpMax commented
probably, this should be removed:
```
concrete_strength_predictor/
datasources_None_test_ds.zip.tar.gz
predictor_None_test_ds.zip.tar.gz
test_ds/
test_ds_csv/
test_predictor/
test_predictor_csv/
```

2021-01-11 14:10 UTC, StpMax commented
If i have current staging version of mindsdb, with predictors and datasources, and then update to your branch, i get two issues:
1. i dont see old datasources in GUI
2. i see old predictors in GUI (but should not), but query to them return error (here https://github.com/mindsdb/mindsdb/blob/distribution_1/mindsdb/interfaces/state/state.py#L70).
May be need add some 'initial migration': if is no `mindsdb.sqlite.db`, then read datasources and predictors and insert them to database?

2021-01-14 01:40 UTC, George3d6 commented
Closing in favor of: https://github.com/mindsdb/mindsdb/pull/1039

2021-01-14 01:40 UTC, closed without merging