docs: llm() function updates
mindsdb/mindsdb pull request #10203
Opened 2024-11-22 15:00 UTC by martyna-mindsdb

## Description

llm() function updates following [this PR](https://github.com/mindsdb/mindsdb/pull/10163)

Fixes #issue_number

## Type of change

- [ ] 📄 This change is a documentation update

2024-11-25 06:28 UTC, ea-rus requested changes

2024-11-25 06:28 UTC, ea-rus commented on docs/mindsdb_sql/functions/llm_function.mdx
> +    LLM_FUNCTION_MODEL
I've checked, in get_llm_config all providers expect model_name param (`config.get("model_name",...`)
So variable name here and for other providers should be: LLM_FUNCTION_MODEL_NAME

2024-11-25 12:54 UTC, martyna-mindsdb commented
Thanks @ea-rus 
I've made the updates.

2024-12-09 12:06 UTC, ea-rus approved these changes

2024-12-09 12:13 UTC, merged