added TextChunkingConfig to FileSplitterConfig
mindsdb/mindsdb pull request #10243
Opened 2024-12-04 23:56 UTC by QuantumPlumber

## Description

Added abatch support for document contextual pre-processing.

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Checklist:

- [ x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ x] I have appropriately commented on my code, especially in complex areas.
- [ x] Necessary documentation updates are either made or tracked in issues.
- [ x] Relevant unit and integration tests are updated or added.

2024-12-04 23:56 UTC, mindsdbadmin commented
<br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request. </sub><sub>Posted by the **CLA Assistant Lite bot**.</sub>

2024-12-05 13:48 UTC, dusvyat approved these changes
lgtm

2024-12-05 13:49 UTC, dusvyat commented on mindsdb/integrations/utilities/rag/splitters/file_splitter.py
> -    ('###', 'Header 3')
nit: would rather put formatting changes in a separate PR to make it clearer what functionality is being change

2024-12-05 13:52 UTC, dusvyat commented on mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
> +        prompts = [
AttributeError: 'list' object has no attribute 'replace' 

You can run [tests/unit/test_document_preprocessor.py](https://github.com/mindsdb/mindsdb/blob/ed7cdb2fa3ff715a1e8fa3fab649418e937929a7/tests/unit/test_document_preprocessor.py) to validate that changes haven't broken anything

2024-12-05 13:53 UTC, dusvyat requested changes
see comment on error, otherwise I think looks good

2024-12-05 14:10 UTC, dusvyat commented on mindsdb/integrations/utilities/rag/splitters/file_splitter.py
> +    text_chunking_config: TextChunkingConfig = TextChunkingConfig(
if we add thus then having chunk_size and chunk_ovlerlap in addition becomes redundant

2024-12-05 14:17 UTC, dusvyat commented on mindsdb/integrations/utilities/rag/splitters/file_splitter.py
> +    recursive_splitter: RecursiveCharacterTextSplitter = RecursiveCharacterTextSplitter(
potentially, text_chunking_config is not full initialised, may be better to move to a  `__post_init__`

 ```
 .
 .
recursive_splitter: RecursiveCharacterTextSplitter = None

    def __post_init__(self):
        if self.recursive_splitter is None:
            self.recursive_splitter = RecursiveCharacterTextSplitter(
                chunk_size=self.text_chunking_config.chunk_size,
                chunk_overlap=self.text_chunking_config.chunk_overlap,
                length_function=self.text_chunking_config.length_function,
                separators=self.text_chunking_config.separators,
            )
```

2024-12-05 14:18 UTC, dusvyat commented on mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
> +            prompts.replace("{{CHUNK_CONTENT}}", chunk_content)
`AttributeError: 'list' object has no attribute 'replace'`

You can run [tests/unit/test_document_preprocessor.py](https://github.com/mindsdb/mindsdb/blob/ed7cdb2fa3ff715a1e8fa3fab649418e937929a7/tests/unit/test_document_preprocessor.py) to validate that changes haven't broken anything

2024-12-05 21:39 UTC, QuantumPlumber commented
I have read the CLA Document and I hereby sign the CLA

2024-12-05 21:43 UTC, QuantumPlumber commented
Closing to re-open

2024-12-05 21:43 UTC, closed without merging