Move integrations to database
mindsdb/mindsdb pull request #1226
Opened 2021-04-23 21:41 UTC by George3d6

2021-04-26 08:21 UTC, StpMax requested changes

2021-04-26 08:21 UTC, StpMax commented on mindsdb/interfaces/storage/db.py
> -    company_id = Column(Integer, unique=True)
Why removed that table? We still need store 'api', 'storage_dir', and probably some other keys on future

2021-04-26 08:21 UTC, StpMax commented on mindsdb/__main__.py
> -    dbw.register_predictors(model_data_arr)
Without that lines only creating integration by http will be possible.

2021-04-30 13:06 UTC, George3d6 commented
Closing in favour of #1231

2021-04-30 13:06 UTC, closed without merging