Add trino kerberos connector
mindsdb/mindsdb pull request #2225
Opened 2022-05-18 15:56 UTC by garvij

Fixes #

## Please describe what changes you made, in as much detail as possible
  - Added trino handler (using kerberos authentication, trino supports many connection types https://trino.io/docs/current/security/authentication-types.html ) Perhaps we can add connection type as a parameter and then plugin in the specific trino-kerberos connector.
mindsdb

2022-05-19 09:38 UTC, ZoranPandovski commented
recheckcla

2022-05-19 09:38 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2022-05-19 13:40 UTC, garvij commented
I have read the CLA Document and I hereby sign the CLA

2022-05-19 13:46 UTC, ZoranPandovski requested changes

2022-05-19 13:46 UTC, ZoranPandovski commented on requirements.txt
> +trino~=0.313.0
Can you please add the dependencies under the `integrations/trino_handler/` directory in a new `requirements.txt` file?

2022-05-20 13:45 UTC, ZoranPandovski approved these changes

2022-05-20 13:45 UTC, merged