Completed: Add closing statement after all tutorials #20
mindsdb/mindsdb pull request #2536
Opened 2022-07-20 15:15 UTC by martyna-mindsdb

Fixes: Add closing statement after all tutorials #20->number from a different repo

## Please describe what changes you made, in as much detail as possible
- added the 'What's Next?' section (marked in red box) at the end of each of the five tutorials (marked in red box)
![image](https://user-images.githubusercontent.com/109554435/180016403-6d2833b0-4eb1-4b17-b6c1-39bb5418b192.png)

mindsdb

2022-07-20 15:29 UTC, Ricram2 requested changes
Minor fix to be done before accepting the PR :).

2022-07-20 15:41 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/sql/tutorials/customer-churn.md
> +* Sign up for a free [MindsDB account](https://cloud.mindsdb.com/?_gl=1*16uh9sn*_ga*ODkzODkzMDc2LjE2NTYwMTgwNjY.*_ga_7LGFPGV6XV*MTY1ODMyNjU0Ni44LjEuMTY1ODMyNjYxMy4w&_ga=2.127186189.1258054943.1658158
Updated the link.

2022-07-20 15:41 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/sql/tutorials/home-rentals.md
> +* Sign up for a free [MindsDB account](https://cloud.mindsdb.com/?_gl=1*16uh9sn*_ga*ODkzODkzMDc2LjE2NTYwMTgwNjY.*_ga_7LGFPGV6XV*MTY1ODMyNjU0Ni44LjEuMTY1ODMyNjYxMy4w&_ga=2.127186189.1258054943.1658158
Updated the link.

2022-07-20 15:41 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/sql/tutorials/house-sales-forecasting.md
> +* Sign up for a free [MindsDB account](https://cloud.mindsdb.com/?_gl=1*16uh9sn*_ga*ODkzODkzMDc2LjE2NTYwMTgwNjY.*_ga_7LGFPGV6XV*MTY1ODMyNjU0Ni44LjEuMTY1ODMyNjYxMy4w&_ga=2.127186189.1258054943.1658158
Updated the link.

2022-07-20 15:41 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md
> +* Sign up for a free [MindsDB account](https://cloud.mindsdb.com/?_gl=1*16uh9sn*_ga*ODkzODkzMDc2LjE2NTYwMTgwNjY.*_ga_7LGFPGV6XV*MTY1ODMyNjU0Ni44LjEuMTY1ODMyNjYxMy4w&_ga=2.127186189.1258054943.1658158
Updated the link.

2022-07-20 15:41 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/sql/tutorials/process-quality.md
> +* Sign up for a free [MindsDB account](https://cloud.mindsdb.com/?_gl=1*16uh9sn*_ga*ODkzODkzMDc2LjE2NTYwMTgwNjY.*_ga_7LGFPGV6XV*MTY1ODMyNjU0Ni44LjEuMTY1ODMyNjYxMy4w&_ga=2.127186189.1258054943.1658158
Updated the link.

2022-07-21 15:30 UTC, ZoranPandovski commented
recheckcla

2022-07-21 15:32 UTC, ZoranPandovski approved these changes

2022-07-21 15:32 UTC, merged