Add BigQuery handler
mindsdb/mindsdb pull request #2636
Opened 2022-08-05 13:22 UTC by ZoranPandovski

This PR adds the initial version of the Google BigQuery handler. 
> Note we need more tests

2022-08-08 16:19 UTC, StpMax requested changes

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
> +            print('INNNNN', result)
todel

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
> +        print('QUERYYY ', query_str)
todel

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
> +from sqlalchemy_bigquery.base import BigQueryDialect
should it be in requirements?

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
> +        result = client.list_tables(dataset_id)
response should be formatted as 'Response'

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/requirements.txt
> +db-types
should it be?

2022-08-08 16:19 UTC, StpMax commented on mindsdb/integrations/handlers/bigquery_handler/tests/test_bigquery_handler.py
> +class PostgresHandlerTest(unittest.TestCase):
BigQueryHandlerTest :)

2022-08-09 10:20 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
> +from sqlalchemy_bigquery.base import BigQueryDialect
Yes, adding it

2022-08-09 11:54 UTC, StpMax approved these changes

2022-08-11 10:33 UTC, merged