Docs issue 2738
mindsdb/mindsdb pull request #2755
Opened 2022-08-23 17:10 UTC by martyna-mindsdb

Fixes #2738 

## Please describe what changes you made, in as much detail as possible
  - worked on collection structure page
[Mongo API - Collection Structure - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408027/Mongo.API.-.Collection.Structure.-.MindsDB.Documentation.pdf)
  - worked on insert databases page
[Mongo API - Databases - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408083/Mongo.API.-.Databases.-.MindsDB.Documentation.pdf)
  - worked on insert predictors page
[Mongo API - Predictors - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408143/Mongo.API.-.Predictors.-.MindsDB.Documentation.pdf)
  - worked on stats page
[Mongo API - Stats() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408239/Mongo.API.-.Stats.-.MindsDB.Documentation.pdf)
  - worked on find page
[Mongo API - Find() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408264/Mongo.API.-.Find.-.MindsDB.Documentation.pdf)
  - worked on delete page
[Mongo API - Delete() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9408279/Mongo.API.-.Delete.-.MindsDB.Documentation.pdf)

mindsdb

2022-08-24 01:47 UTC, Ricram2 requested changes
I have left 2 big questions on the way to "tag" the Mongo commands --JS, and the JSON inside. @ZoranPandovski and @martyna-mindsdb we may need to agree here on a few rules and then rework this PR.

2022-08-24 01:47 UTC, Ricram2 commented on docs/mindsdb-docs/docs/mongo/collection-structure.md
>  ```mql
sql ?

2022-08-24 11:34 UTC, ZoranPandovski commented on docs/mindsdb-docs/docs/mongo/database.md
> +## Using the `#!sql db.databases.insertOne()` Method
We can exclude the #sql tag for now until we have a design for the mql syntax

2022-08-24 11:37 UTC, ZoranPandovski commented on docs/mindsdb-docs/docs/mongo/database.md
>  db.databases.insertOne({
It will work both ways. We need to agree on what style we will follow, maybe the one that is similar to mongo

2022-08-24 13:05 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/mongo/collection-structure.md
>  ```mql
Changed mql to sql.

2022-08-24 13:10 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/mongo/database.md
> +## Using the `#!sql db.databases.insertOne()` Method
Removed `#!sql` tags wherever the code is not SQL.

2022-08-24 13:18 UTC, martyna-mindsdb commented on docs/mindsdb-docs/docs/mongo/database.md
>  db.databases.insertOne({
So to follow the Mongo style, we use the `key: "value"` format where the key is not enclosed and the value is enclosed in double quotation marks. And that would be implemented for all the methods throughout Mongo docs.

@Ricram2 @ZoranPandovski 
Let me know if we agree on that, so I'll implement it. Thanks.

2022-08-25 11:41 UTC, ZoranPandovski commented on docs/mindsdb-docs/docs/mongo/database.md
>  db.databases.insertOne({
Let's do it

2022-08-25 13:41 UTC, martyna-mindsdb commented
Here are the updated pages:

[Mongo API - Collection Structure - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425176/Mongo.API.-.Collection.Structure.-.MindsDB.Documentation.pdf)
[Mongo API - Databases - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425178/Mongo.API.-.Databases.-.MindsDB.Documentation.pdf)
[Mongo API - Predictors - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425183/Mongo.API.-.Predictors.-.MindsDB.Documentation.pdf)
[Mongo API - Stats() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425184/Mongo.API.-.Stats.-.MindsDB.Documentation.pdf)
[Mongo API - Find() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425185/Mongo.API.-.Find.-.MindsDB.Documentation.pdf)
[Mongo API - Delete() - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425186/Mongo.API.-.Delete.-.MindsDB.Documentation.pdf)

2022-08-25 14:50 UTC, merged