☑☑ ADDED Timescaledb Handler
mindsdb/mindsdb pull request #2843
Opened 2022-08-31 12:33 UTC by parthiv11

Fixes #2842 

## Please describe what changes you made, in as much detail as possible
  - All this basic testing done please check this out .
  - You can you timescale db [cloud](https://console.cloud.timescale.com/signup) for TESTING

mindsdb

2022-08-31 14:11 UTC, parthiv11 commented
@ZoranPandovski  Check this out .
It would work as it extends PostgreSQL.

2022-09-13 06:57 UTC, StpMax requested changes
why deleted `informix_handler/README.md`?

2022-09-13 08:08 UTC, parthiv11 commented
@StpMax  Everything solved 

Please Check it out

2022-09-13 08:53 UTC, StpMax approved these changes

2022-09-13 08:54 UTC, merged