Integration xgboost issue2959
mindsdb/mindsdb pull request #3650
Opened 2022-10-24 09:29 UTC by rfsiten

[issue2959] Add xgboost handler and corresponding testcase. (caution, this pr is based on issue2377)

can specify the "task" argument in using block, options: auto, classifier, regressor, reg, cla, a, c, r
the default value is auto.

The handler will do:
1) detect the task type (classify/regress) automatically;
2) fill na in numeric feature column;
3) drop id column automatically;
4) onehot-encoding categorical column;
5) while it's a regressor, val and val__prob will generated.

examples:
···
-- xgboost regress
CREATE PREDICTOR xgboost.titanic_regressor_2
FROM test_mindsdb_proxy
(select Sex, Fare, Pclass, Age from titanic_train_csv) 
PREDICT Age;

select t.Age
from xgboost.titanic_regressor_2 t
inner join test_mindsdb_proxy.titanic_train_csv p;

-- xgboost classify
CREATE PREDICTOR xgboost.titanic_classifier_2
FROM test_mindsdb_proxy
(select * from titanic_train_csv) 
PREDICT Survived;

select t.Survived, t.Survived__prob
from xgboost.titanic_classifier_2 t
inner join test_mindsdb_proxy.titanic_train_csv p
where p.pclass = 1;

···

hey, please review this pr, thank you so much. @paxcema @ZoranPandovski

2022-10-26 10:17 UTC, rfsiten commented
Bayes based parameter search function added. In using block, user can start auto-parameter-tuning by automl=True, and set the number of trail points by trail=30.  More trail points set, more caculation will be done to find the best parameters, also more time will be cost.

2022-11-16 11:11 UTC, rfsiten commented
hey, my friends @ZoranPandovski @paxcema @ea-rus , xgboost is ready !

2022-11-21 19:50 UTC, paxcema requested changes
Great job @rfsiten, in general this is looking good.

I do have one major concern, which is that this introduces a big chunk of automated (and opinionated) feature engineering that we should be testing very well before declaring this as a stable backend. The handler will be experimental for now, so this is fine, but we definitely want to ensure a good test coverage for all the new logic in here in a new PR.

Additionally, some components here (e.g. data type inference and parts of the feature engineering like imputing) will have overlap with new packages we are developing, at which point it may make sense to merge some of the work you've done here into them, so that all other handlers can leverage it. I'll let you know when the time comes :)

Finally, please resolve the merge conflict so that we can try to run CI on this.

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/requirements.txt
> +mindsdb>=22.6.2.1
Update `mindsdb` and `mindsdb_sql` to latest versions :)

2022-11-21 19:50 UTC, paxcema commented on tests/unit/test_xgboost_handler.py
> +from mindsdb.integrations.handlers.merlion_handler.adapters import DefaultForecasterAdapter, SarimaForecasterAdapter, \
Leftovers from Merlion template? If so, remove please

2022-11-21 19:50 UTC, paxcema commented on tests/unit/test_xgboost_handler.py
> +        df = pd.read_csv("/home/drill/Data/titanic/train.csv")
Please change the .csv path to one inside the actual repo (upload a small file if necessary), or maybe to one of our publicly hosted datasets like "Home Rentals"

2022-11-21 19:50 UTC, paxcema commented on tests/unit/test_xgboost_handler.py
> +            train_cols = "PassengerId, Pclass, Sex, Age, SibSp, Parch, Fare, Cabin, Embarked, Survived"
Alternatively, `train_cols += ', Survived'`

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/xgboost_handler.py
> +def to_ts_dataframe(df: pd.DataFrame, time_col=None) -> str:
From what I can see, this handler does not support time series in its current form. Do we need this method, then?

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/xgboost_handler.py
> +class FeatureProcessor:
Just FYI, we are working on a package (`dataprep_ml`) that will be handler-agnostic and may help here once it's fully released.

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/xgboost_handler.py
> +class FeatureProcessor:
We could add support for `category_encoders` there, but this is fine for now.

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/xgboost_handler.py
> +        feature_transofrmer_bytes = self.model_storage.file_get(self.PERSISIT_FEATURE_TRANSFORMER)
typo in variable name

2022-11-21 19:50 UTC, paxcema commented on mindsdb/integrations/handlers/xgboost_handler/xgboost_handler.py
> +                pred_probs_arr.append("{" + ",".join(prob_items) + "}")
Why is `pred_probs_arr` a list of strings? I would imagine a list of lists (with `object` dtype) to be okay for the MindsDB planner + executioner (we do this in the Lightwood handler).

2022-11-21 19:51 UTC, paxcema commented
Oh! And I forgot: please add docstrings in the main components, explaining what they do, what can be customized through `using`, and how they relate to the rest of the handler.

2022-11-22 06:55 UTC, rfsiten commented
@paxcema hey, I will resolve the problems in 1~2 weeks.

2023-01-16 12:15 UTC, ZoranPandovski commented
@rfsiten Do you have any progress here, or do you need help from us?

2023-01-23 10:22 UTC, ea-rus commented on mindsdb/integrations/handlers/xgboost_handler/__init__.py
> +permanent = False
from examples it looks like it should be permanent integration (no need to create xgboost ml engine)
` permanent = False`

2023-04-25 18:56 UTC, paxcema commented
@rfsiten Hi Franky, do you expect to be able to continue working on this in the short term? If not, please let us know. Thanks!

2023-06-22 11:45 UTC, ZoranPandovski commented
@rfsiten Once you have time to make the changes, please re-open the PR

2023-06-22 11:45 UTC, closed without merging