Added Vitess Integration
mindsdb/mindsdb pull request #3789
Opened 2022-10-29 11:01 UTC by parthiv11

Fixes #3682 

## Please describe what changes you made, in as much detail as possible
  - Added Vitess Integration Test it and suggest changes if required

mindsdb

2022-10-29 17:31 UTC, parthiv11 commented
For testing use  [docker ](https://vitess.io/docs/15.0/get-started/vttestserver-docker-image/) or [other options](https://vitess.io/docs/15.0/get-started/)

2022-11-01 13:56 UTC, ZoranPandovski requested changes

2022-11-01 13:56 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/vitess_handler/__init__.py
> +icon_path = 'icon.png'
Please include the icon in the PR

2022-11-01 13:56 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/vitess_handler/README.md
> +The required arguments to establish a connection are:
Isn't the keyspace and schema required?

2022-11-02 13:49 UTC, parthiv11 commented
I think it is working without that parameters

2022-11-15 13:07 UTC, ZoranPandovski approved these changes

2022-11-15 13:07 UTC, merged