🙏🙏Added Materialize Integration
mindsdb/mindsdb pull request #3790
Opened 2022-10-29 11:04 UTC by parthiv11

Fixes #3568 

## Please describe what changes you made, in as much detail as possible
  - Implemented Materialize Database .
  - Please check it and suggest changes, if Required 

mindsdb

2022-10-29 17:37 UTC, parthiv11 commented
For testing either you can apply for [early access](https://materialize.com/register/) or [build from source](https://github.com/MaterializeInc/materialize/tree/main/doc/developer)

2022-12-27 13:19 UTC, ZoranPandovski requested changes
Please make sure the branch is up to date so the tests will not fail

2022-12-27 17:30 UTC, parthiv11 commented
@ZoranPandovski  it's syned now .

You can merge it n0w

2022-12-28 12:31 UTC, ZoranPandovski requested changes

2022-12-28 12:31 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/materialize_handler/materialize_handler.py
> +class MaterializeHandler(YugaByteHandler):
Let's extend the PostgreSQL handler that is most wildly used and better maintained

2022-12-28 12:31 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/materialize_handler/README.md
> +This handler was implemented by extending postres connector.
Minor typo in `postres`

2022-12-28 12:44 UTC, parthiv11 commented
@ZoranPandovski  check the changes

2022-12-29 13:44 UTC, ZoranPandovski approved these changes

2022-12-29 13:44 UTC, merged