created a doc page on building an ml engine
mindsdb/mindsdb pull request #4037
Opened 2022-11-14 12:20 UTC by martyna-mindsdb

Fixes #4021 

## Please describe what changes you made, in as much detail as possible
  - created a doc page on building an ml engine
[Building an ML Engine - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/10002865/Building.an.ML.Engine.-.MindsDB.Documentation.pdf)

mindsdb

2022-11-14 13:22 UTC, paxcema commented on docs/mindsdb-docs/docs/ml_handlers.md
> +# Building an ML Engine
I recommend "machine learning" instead of ML.

2022-11-14 13:22 UTC, paxcema commented on docs/mindsdb-docs/docs/ml_handlers.md
> +In this section, you'll find how to create new ML handlers/engines within MindsDB.
Recommend "machine learning (ML)" instead of "ML".

2022-11-14 14:31 UTC, paxcema requested changes

2022-11-14 14:31 UTC, paxcema commented on docs/mindsdb-docs/docs/contribute/ml_handlers.md
> +ML handlers act as a bridge to any ML framework. You use ML handlers to create ML engines using [the `CREATE ML_ENGINE` command](/sql/create/ml_engine/). So you can create your models using different
Maybe:

> So you can **expose ML models from any supported ML engine as an AI table**.

2022-11-14 14:31 UTC, paxcema commented on docs/mindsdb-docs/docs/contribute/ml_handlers.md
> +The codes for ML handlers are located in the main MindsDB repository under the [/integrations](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations) directory.
I think this is a better way of putting it:

> **The source code** for ML handlers **is**...

2022-11-14 14:31 UTC, paxcema commented on docs/mindsdb-docs/docs/contribute/ml_handlers.md
> +* [Lightwood](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/lightwood_handler)
Maybe put lightwood first 😄 or by alphabetical order.

2022-11-14 21:15 UTC, paxcema approved these changes

2022-11-15 10:49 UTC, ZoranPandovski approved these changes

2022-11-15 10:49 UTC, merged