started working on create ml_engine
mindsdb/mindsdb pull request #4038
Opened 2022-11-14 13:24 UTC by martyna-mindsdb

Fixes #4020 

## Please describe what changes you made, in as much detail as possible
  - started

mindsdb

2022-11-14 14:35 UTC, paxcema requested changes
Made a few requests for small changes, but this is generally OK to go!

2022-11-14 14:35 UTC, paxcema commented on docs/mindsdb-docs/docs/sql/create/ml_engine.md
> +You can create ML engines based on the ML handlers available in MindsDB. And if you can't find the ML handler of your interest, you can always contribute by [building a new ML handler](/contribute/ml
> You can create **machine learning (ML)** engines...

2022-11-14 14:35 UTC, paxcema commented on docs/mindsdb-docs/docs/sql/create/ml_engine.md
> +Please replace the `ml_engine_name`, `handler_name`, and optionally, `argument_key` and `argument_value` with the real values.
Remove the first "the"

2022-11-14 14:35 UTC, paxcema commented on docs/mindsdb-docs/docs/sql/create/ml_engine.md
> +To verify that your ML engine exists, run the command below:
> To verify that your ML engine **was successfully created**, run the command below:

2022-11-14 20:35 UTC, paxcema approved these changes

2022-11-15 10:49 UTC, ZoranPandovski approved these changes

2022-11-15 10:49 UTC, merged