created a general page for mindsdb handlers
mindsdb/mindsdb pull request #4219
Opened 2022-12-14 16:23 UTC by martyna-mindsdb

## Description

- created a general page for mindsdb handlers: 
[Handlers in MindsDB - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10229597/Handlers.in.MindsDB.-.MindsDB.pdf)
- updated a page on database handlers: 
[Building a Database Handler - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10229601/Building.a.Database.Handler.-.MindsDB.pdf)
- updated a page on ml handlers: 
[Building an ML Engine - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10229604/Building.an.ML.Engine.-.MindsDB.pdf)

**Fixes** #4055

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

As in Description.

## Checklist:

- [ ] I have updated the documentation.

2022-12-14 22:28 UTC, paxcema requested changes

2022-12-14 22:28 UTC, paxcema commented on docs/contribute/integrations.mdx
> +In this section, you'll find how to add new integrations/databases to MindsDB.
I'd suggest to rename this file as `docs/contribute/data-handlers.mdx`

2022-12-14 22:28 UTC, paxcema commented on docs/mindsdb-handlers.mdx
> +    The handler's structure is not enforced, and the package design is up to the author.
I would rephrase slightly to:

> All other details of the handler's structure are not enforced, so the author can decide on its design.

2022-12-14 22:28 UTC, paxcema commented on docs/mindsdb-handlers.mdx
> +When it comes to building the response of the public methods, the output should be wrapped by the [mindsdb.integrations.libs.response.HandlerResponse](https://github.com/mindsdb/mindsdb/blob/staging/
Let's specify that this applies to the data handlers. For ML handlers, this is automatically done by an intermediate wrapper (`BaseMLEngineExec`) so the contributor wouldn't need to worry about it.

2022-12-14 22:28 UTC, paxcema commented on docs/contribute/ml-handlers.mdx
> +</Tip>
Similarly to the general intro page, here we should add a tip that mentions there is a wrapper for `BaseMLEngine`s called `BaseMLEngineExec` which is automatically deployed and takes care of modifying the data responses here into something that can be used alongside data handlers.

2022-12-15 13:16 UTC, paxcema approved these changes

2022-12-15 16:34 UTC, ZoranPandovski approved these changes

2022-12-15 16:34 UTC, merged