[Integration]: Quickbooks Integration
mindsdb/mindsdb pull request #5770
Opened 2023-04-23 03:02 UTC by Smyja

## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #5336 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-05-03 12:03 UTC, ZoranPandovski requested changes
Can you please share screenshots or a short video about how this works? Also, I am confused how it works without the native query implementation?

2023-05-04 09:08 UTC, Smyja commented
> Can you please share screenshots or a short video about how this works? Also, I am confused how it works without the native query implementation?

Here's a loom link, i have updated the description also and added the native query.
https://www.loom.com/share/887094aa585a4f0caae6eca6a86f6541

2023-05-05 09:47 UTC, ZoranPandovski requested changes

2023-05-05 09:47 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/quickbooks_handler/quickbooks_handler.py
> +            print('Connected to Quickbooks API')
Please remove the print

2023-05-05 09:47 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/quickbooks_handler/quickbooks_handler.py
> +            print('Disconnected from Quickbooks API')
Same here

2023-05-05 09:59 UTC, Smyja commented on mindsdb/integrations/handlers/quickbooks_handler/quickbooks_handler.py
> +            print('Connected to Quickbooks API')
done

2023-05-05 09:59 UTC, Smyja commented on mindsdb/integrations/handlers/quickbooks_handler/quickbooks_handler.py
> +            print('Disconnected from Quickbooks API')
done

2023-05-05 10:37 UTC, Smyja commented
I have resolved the issues @ZoranPandovski

2023-05-05 13:17 UTC, ZoranPandovski approved these changes

2023-05-05 13:17 UTC, merged