PayPal Integration
mindsdb/mindsdb pull request #6289
Opened 2023-05-25 19:58 UTC by MinuraPunchihewa

I have implemented the new integration for PayPal. For now, I have added support for querying Payments (payments) using the handler.

After some initial testing, it looks to be working as expected. Please do let me know if there is anything that I have missed or if there are any bugs.

The details of how this handler has been implemented has been outlined in the README.md file.

2023-05-26 11:52 UTC, ZoranPandovski requested changes
Looks great. Since we are already using the SELECTQueryParser here to can we add it as a util or helper?

2023-05-27 06:39 UTC, MinuraPunchihewa commented
Hey @ZoranPandovski,
I've added the `query_utilities` to a new `utilities` package and implemented the handler.

2023-05-27 06:45 UTC, MinuraPunchihewa commented
Once this is approved, I will refactor the other handlers I developed to use these `utilities` as well.

2023-05-29 14:43 UTC, ZoranPandovski approved these changes

2023-05-29 14:43 UTC, merged