Add Mendeley handler
mindsdb/mindsdb pull request #6434
Opened 2023-06-02 15:28 UTC by Christinanik251

## Description

I added the Mendeley handler. I have tested the handler and it seems to work finely, however if any problem is detected please let me know and I will look into it! Also please let me know if any changes in the implementation are needed. In order to establish a connection with the API it is firstly needed for the application to be registered at Mendeley's website (there are clearer instructions at https://dev.mendeley.com/reference/topics/application_registration.html). Since I didn't consider myself authorized to use mindsdb's name or information, I have used credentials of my own purely for testing reasons (the credentials are used in the connect method and should be changed should the implementation be accepted). Kind regards! 

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.
<img width="938" alt="Στιγμιότυπο 2023-06-02, 6 25 15 μμ" src="https://github.com/mindsdb/mindsdb/assets/93385939/4bfc07e6-9196-4c44-ac70-a2952832694e">
<img width="1677" alt="Στιγμιότυπο 2023-06-02, 4 46 48 μμ" src="https://github.com/mindsdb/mindsdb/assets/93385939/d144c5c6-87fe-43df-a7a2-c5a3b72f6ba3">
<img width="1406" alt="Στιγμιότυπο 2023-06-02, 4 47 52 μμ" src="https://github.com/mindsdb/mindsdb/assets/93385939/732ae4a9-1baf-450f-aa00-5910e2abaafb">

2023-06-07 14:34 UTC, ZoranPandovski requested changes

2023-06-07 14:34 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/mendeley_handler/README.md
> +  PARAMETERS = {};
Since by default we don't need params better to remove it from here

2023-06-07 14:34 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/mendeley_handler/__about__.py
> +__author__ = 'MindsDB Inc'
Please add yourself as author :)

2023-06-07 14:34 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/mendeley_handler/__init__.py
> +
Can we add an mendeley icon so we can add it to the GUI?

2023-06-08 21:11 UTC, Christinanik251 commented
Hello! Thank you very much for taking the time to look over my code and I am sorry for not responding sooner. I have implemented the requested changes. If there is a need for further changes please let me know and I will work on them right away. Kind regards!

2023-06-09 11:41 UTC, ZoranPandovski approved these changes
Thanks, feel free to check other open integrations issues or propose a new one :raised_hands:

2023-06-09 11:41 UTC, merged