Use torch.multiprocessing only if installed
mindsdb/mindsdb pull request #6463
Opened 2023-06-05 19:26 UTC by ilia-tsyplenkov

## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-06-19 08:18 UTC, AndrewFarley requested changes
Needs work, see comments

2023-06-19 08:18 UTC, AndrewFarley commented on mindsdb/__main__.py
> +    import multiprocessing as mp
NOTE: There's a bunch of commands below in "init" that use mp.* commands, which means they will fail I believe.  We need them to find alternatives.

2023-06-21 16:56 UTC, ilia-tsyplenkov commented on mindsdb/api/http/start.py
> +    import multiprocessing as mp
torch.multiprocessing has same public API as python.multiprocessing. https://docs.python.org/3/library/multiprocessing.html#multiprocessing.cpu_count

2023-06-21 16:57 UTC, ilia-tsyplenkov commented on mindsdb/integrations/libs/ml_exec_base.py
> +    import multiprocessing as mp
torch.multiprocessing has same public API as python.multiprocessing. https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context

2023-06-21 16:57 UTC, ilia-tsyplenkov commented on mindsdb/integrations/utilities/processes.py
> +    import multiprocessing as mp
torch.multiprocessing has same public API as python.multiprocessing. https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context

2023-10-13 11:38 UTC, ZoranPandovski commented
@tomhuds Should we close this?

2024-08-14 08:51 UTC, ZoranPandovski commented
Closing as outdated

2024-08-14 08:51 UTC, closed without merging