Testing snowflake handler manually
mindsdb/mindsdb pull request #6515
Opened 2023-06-08 15:51 UTC by NishitSingh2023

## Description

Running the commands provided in the issue, recording the observations in `mindsdb/integrations/handlers/snowflake_handler/Manual_QA.md.`

**Fixes** [issue](https://github.com/mindsdb/mindsdb/issues/6222)

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

The manual QA for the SnowFlake handler is completed successfully as stated.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-06-08 15:55 UTC, ZoranPandovski requested changes
Thanks can you please add it as a new section in the README instead of removing the old one?

2023-06-08 16:18 UTC, NishitSingh2023 commented
@ZoranPandovski have updated the code to append the observations in the readme file

2023-06-09 11:45 UTC, ZoranPandovski approved these changes

2023-06-09 11:45 UTC, merged

2023-06-09 11:45 UTC, ZoranPandovski commented
Thanks @NishitSingh2023 please check other `help-wanted` issues :raised_hands: