Update Mysql handler documentation
mindsdb/mindsdb pull request #6623
Opened 2023-06-16 17:01 UTC by alejandrovillegas

## Description

Update MySQL information to tart using it on GUI forms

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-06-18 14:17 UTC, ZoranPandovski approved these changes

2023-06-18 14:17 UTC, ZoranPandovski requested changes

2023-06-18 14:17 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
> +    },
We are missing the schema as optional param

2023-06-21 11:26 UTC, StpMax approved these changes

2023-06-21 11:26 UTC, merged