add optional cpu huggingface requirements file
mindsdb/mindsdb pull request #6781
Opened 2023-07-05 22:48 UTC by hamishfagg

Also modifies setup.py to handle extra requirements files in the form `requirements<x>.txt` inside a handler folder. This allows us multiple setups of a handler (like `huggingface_cpu`.

2023-07-20 11:41 UTC, ea-rus requested changes

2023-07-20 11:41 UTC, ea-rus commented on mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
> +mindsdb>=22.6.2.1
why mindsdb dependency here? handlers don't use mindsdb

2023-07-20 11:42 UTC, ea-rus commented
So for huggingface with cpu command is going to be like this, right?
`pip install mindsdb[huggingface_cpu]`

2023-10-24 22:40 UTC, hamishfagg commented
@ea-rus ive just updated this so take another look.

unfortunately it has to be installed with `pip install --extra-index-url https://download.pytorch.org/whl/ .[huggingface_cpu]`, there's no way around having to specify the extra URL.

2023-11-20 23:06 UTC, closed without merging

2023-11-20 23:09 UTC, hamishfagg commented
fixed by #8395