Bring your own model
mindsdb/mindsdb pull request #681
Opened 2020-09-08 15:58 UTC by George3d6

2020-09-08 15:59 UTC, mindsdbadmin commented
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

2020-09-14 09:27 UTC, StpMax requested changes
need to remove `my_model.zip` and probably `test_custom_model/model.py`

2020-09-14 09:27 UTC, StpMax commented on mindsdb/interfaces/custom/custom_models.py
> +        shutil.move(os.path.join(self._dir(new_name) + f'{name}.py'), os.path.join(self._dir(new_name) ,f'{new_name}.py'))
here probable need add register/unregister_predictor

2020-09-14 09:27 UTC, StpMax commented on mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
> +            mdb.learn(insert['name'], ds, insert['predict'], kwargs)
I don't like this not obvious behavior. Probably in future we should add 'update' statement for such cases.

2020-09-14 09:27 UTC, StpMax commented on mindsdb/api/http/initialize.py
> +from mindsdb.utilities.config import Config
unused import

2020-09-14 09:27 UTC, StpMax commented on mindsdb/api/http/namespaces/predictor.py
> +class PredictorColumns(Resource):
This class name already exist

2020-09-14 09:27 UTC, StpMax commented on mindsdb/integrations/clickhouse/clickhouse.py
> +                print(model_meta)
unnecessary print

2020-09-14 14:34 UTC, merged