add read me for chromadb, popularity, lightfm and writer handlers
mindsdb/mindsdb pull request #6975
Opened 2023-07-27 21:52 UTC by dusvyat

## Description

add read me files for chromadb, writer, popularity and lightfm

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-07-28 18:54 UTC, paxcema requested changes
Left a few observations on typos, but mostly LGTM!

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/chromadb_handler/Manual_QA.md
> +# Welcome to the MindsDB Manual QA Testing for Cassandra Handler
Rename all references to `Cassandra` with `ChromaDB` 😬

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/chromadb_handler/Manual_QA.md
> +## Testing Cassandra Handler with [Dataset Name](URL to the Dataset)
Also, remove this initial section with instructions.

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/chromadb_handler/README.md
> +This handler uses `chromadbd` python library connect to a chromadb instance, it uses langchain to make use of their pre-existing semantic search functionality
typo: `chromadbd`

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/chromadb_handler/README.md
> +* `chroma_api_impl`: the api implementation, likely should be `rest`
Would recommend specifying what other choices exist for this param

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/chromadb_handler/README.md
> +* `embedding_function`: the embedding function to use to get embeddings from input text or search text
Maybe worth pointing out that huggingface hub model strings work here

2023-07-28 18:54 UTC, paxcema commented on mindsdb/integrations/handlers/lightfm_handler/README.md
> +-- Create Writer engine
typo: reference to `Writer`

2023-08-25 18:03 UTC, paxcema commented
Friendly reminder to address the requested changes @dusvyat 👀

2023-09-07 00:03 UTC, dusvyat commented
> Friendly reminder to address the requested changes @dusvyat 👀

@paxcema sorry completely forgot about this one, just fixed the typos you pointed out. Please feel free to +1 and merge when you get a sec

2023-09-07 00:05 UTC, paxcema approved these changes

2023-09-07 00:06 UTC, merged