Self argument probing
mindsdb/mindsdb pull request #7087
Opened 2023-08-10 19:00 UTC by yuhuishi-convect

## Description

This adds a static analyzer for the ML engines.
It parses the source code of the ML engine class implementation, 
find how the argument `args` dict is used.

For example, if there is a line `args['some_key']`, then likely there is an argument `some_key` which is required.
It adds the parsed results to the `information_schema.handlers` table.

Next step: when user provides an argument which is not known to the parsed arguments list, we raise a "soft" error to them.

**Fixes** #6846

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

2023-08-16 20:00 UTC, paxcema requested changes
Generally looks good to me. There is one bit that I think may be a bit of an edge case and could prove buggy. But otherwise, I believe this will be an extremely useful addition. Nice one @yuhuishi-convect!

2023-08-21 23:03 UTC, yuhuishi-convect commented on mindsdb/integrations/libs/base.py
> +        unique_arg_keys = set([(r["name"], r["required"]) for r in visitor.arg_keys])
Yes nice catch!

2023-08-21 23:03 UTC, yuhuishi-convect commented on tests/unit/test_arg_probing.py
> +            args["test_required2"] = "default"  # this should be ignored
👍

2023-08-22 18:23 UTC, yuhuishi-convect commented
@paxcema fixed some issues according to the comments

2023-08-22 20:07 UTC, paxcema approved these changes

2023-08-25 06:06 UTC, merged