Create LlamaIndex documentation and Manual_QA.md
mindsdb/mindsdb pull request #7328
Opened 2023-09-13 16:24 UTC by chandrevdw31

## Description

Manual QA tests and documentation for LlamaIndex

**Fixes** #6889

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-09-14 08:06 UTC, martyna-mindsdb commented on docs/integrations/ai-engines/llamaindex.mdx
> +DESCRIBE qa_blackrock```
Please move ``` to the next line, like this:

> \```sql
> DESCRIBE qa_blackrock
> \```

2023-09-14 08:06 UTC, martyna-mindsdb commented on docs/integrations/ai-engines/llamaindex.mdx
> +`The best long term investment with minimal risks for private investors is a diversified portfolio of low-cost index funds. These funds typically track a broad market index, such as the S&P 500, and
Please put this answer in a code block, like this:

> \```
> The best long term investment with minimal risks for private investors is a diversified portfolio of low-cost index funds. These funds typically track a broad market index, such as the S&P 500, and provide exposure to a wide variety of publicly traded companies with minimal risk. Blackrock is one of the largest asset management companies in the world, and offers a range of index funds, exchange-traded funds, and other investment products for private investors.
> \```

2023-09-14 08:06 UTC, martyna-mindsdb commented on docs/integrations/ai-engines/llamaindex.mdx
> +| `engine`                               | The engine used,which is Llamaindex.       |
Please update description to: `The engine name - here, llamaindex.`

2023-09-14 08:06 UTC, martyna-mindsdb commented on docs/integrations/ai-engines/llamaindex.mdx
> +| `reader`                               |The reader that reads the data/webpage.     |
Please add `source_url_link` after `reader`. And description: `The webpage link.`

2023-09-14 13:29 UTC, ZoranPandovski requested changes

2023-09-14 13:29 UTC, ZoranPandovski commented on docs/assets/tutorials/llamaindex/.gitkeep
> +For llamaindex images
Let's remove this file

2023-09-14 16:16 UTC, chandrevdw31 commented on docs/assets/tutorials/llamaindex/.gitkeep
> +For llamaindex images
removed

2023-09-15 12:57 UTC, martyna-mindsdb approved these changes

2023-09-15 13:07 UTC, ZoranPandovski approved these changes

2023-09-15 13:07 UTC, merged