Documentation for the MediaWiki Handler
mindsdb/mindsdb pull request #7390
Opened 2023-09-21 09:01 UTC by MinuraPunchihewa

Added the documentation for the MediaWiki handler.

2023-09-21 11:59 UTC, ZoranPandovski requested changes
Also please add the link to this page in the Integrations nav item

2023-09-21 11:59 UTC, ZoranPandovski commented on docs/integrations/app-integrations/mediawiki.mdx
> +This is the implementation of the ClickHouse data handler for MindsDB.
It mentions ClickHouse

2023-09-21 11:59 UTC, ZoranPandovski commented on docs/integrations/app-integrations/mediawiki.mdx
> +```
We need docs for more complex  queries as:

```
SELECT * 
FROM mediawiki_datasource.pages
WHERE title = 'Earth'
ORDER BY pageid
LIMIT 5
```

2023-09-22 09:37 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/mediawiki.mdx
> +This is the implementation of the MediaWiki data handler for MindsDB.
Let's say `MediaWiki app handler` instead of `MediaWiki data handler`.

2023-09-22 09:37 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/mediawiki.mdx
> +## Implementation
To keep app doc pages consistent, let's rename this chapter to `## Connection` and move the `CREATE DATABASE` statement to this chapter.

2023-09-22 09:37 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/mediawiki.mdx
> +
Let's move the `CREATE DATABASE` statement here.

> In order to make use of this handler and connect to the MediaWiki API in MindsDB, the following syntax can be used:
> 
> \```sql
> CREATE DATABASE mediawiki_datasource
> WITH ENGINE = 'mediawiki'
> \```

2023-09-22 09:37 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/mediawiki.mdx
> +~~~~sql
Please use the code block like above.

2023-09-22 09:37 UTC, martyna-mindsdb commented on docs/mint.json
> +            "integrations/app-integrations/mediawiki"
Let's list it in alphabetical order. So `"integrations/app-integrations/mediawiki"` would come after `"integrations/app-integrations/hackernews",`.

2023-09-22 09:59 UTC, MinuraPunchihewa commented
@martyna-mindsdb Thank you for comments! I have made the changes requested.

2023-09-22 10:20 UTC, martyna-mindsdb commented
Thanks @MinuraPunchihewa 

There is one more thing: please add `<Card title="MediaWiki" icon="link" href="/app-integrations/mediawiki"></Card>` to the `docs/integrations/data-sources-overview.mdx` at line 26 (after hackernews).

We keep overview of all data sources there.

2023-09-22 10:43 UTC, MinuraPunchihewa commented
> Thanks @MinuraPunchihewa
> 
> There is one more thing: please add `<Card title="MediaWiki" icon="link" href="/app-integrations/mediawiki"></Card>` to the `docs/integrations/data-sources-overview.mdx` at line 26 (after hackernews).
> 
> We keep overview of all data sources there.

@martyna-mindsdb Its, done!

2023-09-22 11:23 UTC, martyna-mindsdb approved these changes

2023-09-22 11:27 UTC, merged