Pytorch_tabular Integration
mindsdb/mindsdb pull request #7463
Opened 2023-09-30 18:32 UTC by pranavvp16

model_storage for trained model is remaining to add . Is there any documentation regarding how to save a pytorch model using the self.model_storage #6387

2023-10-02 13:05 UTC, paxcema commented
> Is there any documentation regarding how to save a pytorch model using the self.model_storage

It is quite similar to what is mentioned in step 4 of the [step-by-step guide here](https://docs.mindsdb.com/contribute/ml-handlers): `engine_storage` saves anything that is common to all models created with this engine for the user, and `model_storage` can be used to save anything that is model-specific.

In terms of what methods you can use, check its source [here](https://github.com/mindsdb/mindsdb/blob/f7516a6252f26f4e437189195e1f1042486ac221/mindsdb/interfaces/storage/model_fs.py#L124). I don't think we have API docs for it yet.

Finally, I recommend checking other engines for example usage.

2023-10-15 11:51 UTC, pranavvp16 commented
pytorch tabular is working now @paxcema @ZoranPandovski 
![image](https://github.com/mindsdb/mindsdb/assets/94780581/311a8e88-0120-4f70-b6df-4cbc88ad5188)
![image](https://github.com/mindsdb/mindsdb/assets/94780581/9290a1b7-60b0-4498-8489-6d73e35c3f56)

2023-10-16 18:44 UTC, paxcema commented on mindsdb/integrations/handlers/pytorch_tabular_handler/pytorch_tabular_handler.py
> +                raise Exception(f"Please specify layers in format : '128-64-32'")
Out of ignorance (no experience with pytorch tabular yet), why is a formatted string preferred to a list of integers?

Our SQL parser does support something like this:

```sql
CREATE MODEL
...
USING layers = ['128', '64', '32']  -- integers also work: [128, 64, 32] 
```

2023-10-16 19:29 UTC, paxcema requested changes

2023-10-16 19:29 UTC, paxcema commented on mindsdb/integrations/handlers/pytorch_tabular_handler/README.md
> +FROM files. California Housing as t
These spaces will likely raise a parsing error as well

2023-10-16 19:29 UTC, paxcema commented on mindsdb/integrations/handlers/pytorch_tabular_handler/README.md
> +FROM files. California Housing as t
I noticed it is fixed on the screenshots you've provided, which is great. Let's just make sure this example is also updated.

2023-10-19 13:27 UTC, pranavvp16 commented
@paxcema any updates on this ??

2023-10-19 22:42 UTC, paxcema requested changes
Nice, there are two pending items before we can merge this:
1. A working set of unit tests for the handler
2. Fix all linting errors that `flake8` shows. You can see them in the Github actions for the last commit.

2023-10-19 22:42 UTC, paxcema commented on tests/unit/executor_test_base.py
> +        r = db.Integration(name="rag", data={}, engine="rag")
This change seems unnecessary, please remove this.

2023-10-27 13:44 UTC, pranavvp16 commented
@ZoranPandovski I have pull the staging and all the tests pass now

2023-10-31 13:25 UTC, ZoranPandovski requested changes
Thanks, let's solve the conflicts before we merge this

2023-11-28 09:46 UTC, paxcema commented
Hey @pranavvp16 there is still one file with a merge conflict, can you check please?

2023-11-28 14:17 UTC, pranavvp16 commented
@paxcema I have fixed the merge conflicts

2023-12-12 08:16 UTC, paxcema commented
Nice! Seems like there is still a problem in the requirements check though 🔍, related to `setuptools`. Can you please fix it?

2024-02-23 17:51 UTC, closed without merging