feat: added inventory table shopify implementation
mindsdb/mindsdb pull request #7493
Opened 2023-10-02 21:02 UTC by sahil9001

## Description

Please include a summary of the change and the issue it solves. 
This PR implements the `Inventory` table from shopify API

Fixes #7488 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-03 10:07 UTC, ZoranPandovski commented
recheckcla

2023-10-03 10:07 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-10-03 12:00 UTC, martyna-mindsdb commented
This has been implemented. You can look at other hacktoberfest issues.

2023-10-03 12:31 UTC, sahil9001 commented
Well @martyna-mindsdb , is it fair to close the first PR (which was mine) and accept the second one? I think I was not given chance to even learn about this and other person's PR got accepted much before I can even comprehend. Anyways, no issues with it, just a thing from which I feel discouraged to make PRs on this repo.

2023-10-03 13:01 UTC, MinuraPunchihewa requested changes

2023-10-03 13:01 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
> +    """The Shopify Inventory Table implementation"""
Shopify Inventory Items Table will make this more clear.

2023-10-05 10:25 UTC, martyna-mindsdb commented
@sahil9001 
Please address the review comments above and provide screenshots of successful tests.

2023-10-06 11:00 UTC, ZoranPandovski commented
Solved by https://github.com/mindsdb/mindsdb/pull/7494

2023-10-06 11:00 UTC, closed without merging