LAST keyword support
mindsdb/mindsdb pull request #7518
Opened 2023-10-03 14:57 UTC by ea-rus

## Description

TODO

This query should return no record on first run.  And show only new records (with new last_date values) on every next run
```
select *
  from my_pg.tasks
where last_date > last
```

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-11 11:37 UTC, StpMax requested changes

2023-10-12 10:46 UTC, ea-rus commented on mindsdb/integrations/handlers/cloud_spanner_handler/README.md
> +    "dialect": "postgres" // optinonal, default is 'googlesql'
fixed

2023-10-12 10:46 UTC, ea-rus commented on mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
> +        # if isinstance(data, ASTNode):
removed

2023-10-12 10:46 UTC, ea-rus commented on mindsdb/interfaces/query_context/context_controller.py
> +contextController = ContextController()
name replaced to query_context_controller

2023-10-12 10:46 UTC, ea-rus commented on mindsdb/interfaces/database/projects.py
> +        return view_meta
No, it was bug, i removed it.

2023-10-12 10:47 UTC, ea-rus commented on mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py
> +        view_meta = renderer.get_string(view_query_ast, with_failback=True)
removed render here, I think we can use AST instead

2023-10-12 10:47 UTC, ea-rus commented on mindsdb/interfaces/query_context/context_controller.py
> +class ContextController:
added docstrings for new classes

2023-10-12 10:47 UTC, ea-rus commented on mindsdb/interfaces/storage/db.py
> +class QueryContext(Base):
done

2023-10-12 10:48 UTC, ea-rus commented on mindsdb/interfaces/query_context/last_query.py
> +        self.query = query
replaced, now are:
- query_orig is original query
- query is modified

2023-10-12 10:49 UTC, ea-rus commented on mindsdb/interfaces/query_context/last_query.py
> +        query = copy.deepcopy(self.query_in)
changed: deepcopy is executed after analyzing of query and only if query contents LAST

2023-10-12 13:57 UTC, StpMax approved these changes

2023-10-12 14:28 UTC, merged