Changed the default stdouts
mindsdb/mindsdb pull request #752
Opened 2020-10-04 12:51 UTC by pushp1997

Fixes #741 

## Please describe what changes you made, in as much detail as possible
  - Have changed the default STDOUT message and if verbose is not given a NOTE is displayed stating that the verbose is off:
![SS without -v](https://user-images.githubusercontent.com/19623154/95015792-96225880-066c-11eb-9597-c4026496032e.png)

  - If --verbose is not given log level is set to "ERROR" else it is set to "INFO" (NOTE: This was already done, yo may find it in __min__.py file, line 148):
![image](https://user-images.githubusercontent.com/19623154/95015851-ff09d080-066c-11eb-9b1a-9711110ec10d.png)

mindsdb

2020-10-04 12:52 UTC, pushp1997 commented
Please let me know if any other change is required.

2020-10-06 13:19 UTC, ZoranPandovski commented
recheckcla

2020-10-06 13:19 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

2020-10-06 13:58 UTC, George3d6 commented
@pushp1997 can you please sign the CLA ? We need it signed for external contributors since the code of Mindsdb is licensed under GPL

2020-10-08 11:24 UTC, pushp1997 commented
I have read the CLA Document and I hereby sign the CLA

2020-10-12 19:37 UTC, George3d6 requested changes

2020-10-12 19:37 UTC, George3d6 commented on mindsdb/__main__.py
> +                else: # api['name'] == http
Should be an `if` here since both can start at once

2020-10-12 19:37 UTC, George3d6 commented on mindsdb/__main__.py
> +    print('\n' + '='*7 + '\n') # print divider
can you move these back to their original position ? If not, why did you move these down ?

2020-10-26 16:58 UTC, George3d6 commented
@pushp1997 will close this for now, let me know if you want to start back up on it and we can reopen

2020-10-26 16:58 UTC, closed without merging