added newsappi docs
mindsdb/mindsdb pull request #7544
Opened 2023-10-04 12:06 UTC by Better-Boy

## Description

Added docs for newsapi integration.

Fixes #7522 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-04 12:33 UTC, ZoranPandovski requested changes
Thanks, please just also add link to it in https://github.com/mindsdb/mindsdb/blob/staging/docs/mint.json#L781

2023-10-04 12:45 UTC, Better-Boy commented
> Thanks, please just also add link to it in https://github.com/mindsdb/mindsdb/blob/staging/docs/mint.json#L781

Done

2023-10-04 14:33 UTC, martyna-mindsdb approved these changes

2023-10-05 11:27 UTC, ZoranPandovski approved these changes

2023-10-05 11:27 UTC, merged