Fixes #7478
mindsdb/mindsdb pull request #7616
Opened 2023-10-06 22:54 UTC by victorian177

## Description
Summary of changes made:
- Created a handler for **OrientDB**.
- Implemented functions for connecting to the **OrientDB** database i.e. `connect`, `disconnect`, and `check_connection`.
- Implemented functions for querying the **OrientDB** database i.e. `query`, `native_query`, `get_tables`, and `get_columns`.
- Implemented a unit test class for the **OrientDB** handler.

Fixes #7478

## Type of change
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process
To ensure the changes are working as expected:
 - [x]   Test Location: mindsdb/mindsdb/integrations/handlers/orientdb_handler/tests/test_orientdb_handler.py
 - [x]   Verification Steps: Run the following command in MindsDB Web Editor
 ```SQL
 CREATE DATABASE example_display_name  -- display name for database.
WITH ENGINE = 'orientdb',             -- name of the MindsDB handler
PARAMETERS = {
  "user": "root",          -- Your database user.
  "password": "root",      -- Your password.
  "host": "127.0.0.1",     -- Host (It can be an IP or a URL).
  "port": 2424,            -- Default port is 2424.
  "database": "example_db" -- The name of your database.
};
```
It requires that you have an instance of **OrientDB** server running with the database created.
Run: `docker run -d -p 2424:2424 -p 2480:2480 orientdb:2.2`.

## Checklist:
- [x] My code follows the style guidelines(PEP 8) of MindsDB by running the `black` Python formatter.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

## Some things to note
- The Python wrapper for OrientDB i.e. `pyorient` only works with **OrientDB** version 2.2. `pyorient` was last updated in 2017.

2023-10-07 07:31 UTC, victorian177 commented
I keep getting this [error message](https://github.com/mindsdb/mindsdb/actions/runs/6439663582/job/17487606776?pr=7616). It states that it is a problem with the tests folder.

2023-10-09 09:41 UTC, ZoranPandovski requested changes
Thanks. Please check the comments and also:
* Remove Manual QA file
*  Exclude the changes in HTTP API and the unit/ml handlers tests

2023-10-09 09:41 UTC, ZoranPandovski commented on docker/executor.Dockerfile
> +# COPY ../mindsdb /mindsdb/mindsdb
Please exclude this File from the PR

2023-10-09 09:41 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/orientdb_handler/orientdb_handler.py
> +        if self.is_connected is False:
Can we avoid nested try/except please? Use separate functions to handle the client creation and db_open

2023-10-10 11:50 UTC, ZoranPandovski requested changes
Please make sure your branch is up to date with staging and exclude all files where you didn't add changes

2023-10-12 11:13 UTC, ZoranPandovski commented
Please let's re-open another PR, it is hard to review this one with 8000 lines changed

2023-10-13 11:43 UTC, closed without merging