Adding "YouTube Insights with MindsDB SDK" to Application Showcase
mindsdb/mindsdb pull request #7770
Opened 2023-10-13 20:08 UTC by ritwickrajmakhal

## Description

In this pull request, I have added a new application to the "Applications with MindsDB" section in the `docs/applications_showcase.mdx` file.

The application is titled "YouTube Insights with MindsDB SDK". This is a Flask web application that uses the MindsDB SDK to analyze sentiment and summarize comments for a given YouTube video. This project provides valuable insights into the sentiments expressed in YouTube video comments and provides a summarized overview of the comments.

I believe this project serves as a good example of MindsDB's capabilities, and I hope that showcasing it will provide a useful learning tool for the MindsDB community.

## Type of change
- [x] 📄 This change requires a documentation update

## Additional Media:
![Screenshot_20231013_235523](https://github.com/mindsdb/mindsdb/assets/100060023/18f909a4-2178-474e-86fe-9eb7b42de5f9)
- [x] I have attached a screenshot of my project.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

2023-10-26 11:53 UTC, ZoranPandovski requested changes
Hey @ritwickrajmakhal is this working? I wasn't able to get any response from the app

2023-10-26 12:51 UTC, ritwickrajmakhal commented
Yes the deployed app is working correctly:
Here is the demo:
1. [Click here](https://ritwickrajmakhal.github.io/ytinsights/) to see the app.

https://github.com/mindsdb/mindsdb/assets/100060023/2d172e75-4fcd-4b72-9cb2-c143c10db75e

2. I just tested my app on my windows machine using the code of [backend](https://github.com/ritwickrajmakhal/youtube-insights) for my app.
Here is the terminal logs:
```pwsh
PS D:\> git clone https://github.com/ritwickrajmakhal/youtube-insights.git
Cloning into 'youtube-insights'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 94 (delta 47), reused 73 (delta 29), pack-reused 0Receiving objects:  72% (68/94), 556.00 KiB | 53.00 KiB/Receiving objects: 100% (94/94), 563.76 KiB | 34.00 KiB/s, done.

Resolving deltas: 100% (47/47), done.
PS D:\> cd youtube-insights
PS D:\youtube-insights> python -m venv venv
PS D:\youtube-insights> venv\Scripts\activate
(venv) PS D:\youtube-insights> pip install -r requirements.txt
Collecting Flask
  Using cached flask-3.0.0-py3-none-any.whl (99 kB)
Collecting python-dotenv
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting mindsdb-sdk
  Using cached mindsdb_sdk-2.0.0-py3-none-any.whl
Collecting Flask-Cors
  Using cached Flask_Cors-4.0.0-py2.py3-none-any.whl (14 kB)
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting blinker>=1.6.2
  Using cached blinker-1.6.3-py3-none-any.whl (13 kB)
Collecting Jinja2>=3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting Werkzeug>=3.0.0
  Using cached werkzeug-3.0.1-py3-none-any.whl (226 kB)
Collecting pandas>=1.3.5
  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)
Collecting mindsdb-sql<0.8.0,>=0.7.0
  Using cached mindsdb_sql-0.7.3-py3-none-any.whl (131 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting sqlalchemy<3.0.0,>=2.0.0
  Using cached SQLAlchemy-2.0.22-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting pytest>=5.4.3
  Using cached pytest-7.4.3-py3-none-any.whl (325 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Collecting numpy>=1.22.4
  Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-3.0.1-cp310-cp310-win_amd64.whl (287 kB)
     |████████████████████████████████| 287 kB 467 kB/s
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.1-cp310-cp310-win_amd64.whl (98 kB)
Installing collected packages: typing-extensions, tomli, six, pluggy, packaging, MarkupSafe, iniconfig, greenlet, exceptiongroup, colorama, Werkzeug, urllib3, tzdata, sqlalchemy, pytz, python-dateutil, pytest, numpy, Jinja2, itsdangerous, idna, click, charset-normalizer, certifi, blinker, requests, pandas, mindsdb-sql, Flask, python-dotenv, mindsdb-sdk, Flask-Cors
Successfully installed Flask-3.0.0 Flask-Cors-4.0.0 Jinja2-3.1.2 MarkupSafe-2.1.3 Werkzeug-3.0.1 blinker-1.6.3 certifi-2023.7.22 charset-normalizer-3.3.1 click-8.1.7 colorama-0.4.6 exceptiongroup-1.1.3 greenlet-3.0.1 idna-3.4 iniconfig-2.0.0 itsdangerous-2.1.2 mindsdb-sdk-2.0.0 mindsdb-sql-0.7.3 numpy-1.26.1 packaging-23.2 pandas-2.1.1 pluggy-1.3.0 pytest-7.4.3 python-dateutil-2.8.2 python-dotenv-1.0.0 pytz-2023.3.post1 requests-2.31.0 six-1.16.0 sqlalchemy-2.0.22 tomli-2.0.1 typing-extensions-4.8.0 tzdata-2023.3 urllib3-2.0.7
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'D:\youtube-insights\venv\Scripts\python.exe -m pip install --upgrade pip' command.
```
After that I have created a file called `.env` within the project directory, i.e `youtube-insights/` and added all the enviroment variables:

```
MINDSDB_EMAIL=your-mindsdb-email
MINDSDB_PASSWORD=your-mindsdb-password
YOUTUBE_API_KEY=your-youtube-api-key
OPENAI_API_KEY=your-openai-api-key
```
Then I go back to my terminal and ran the following:
```pwsh
(venv) PS D:\youtube-insights> python app.py
Connected to MindsDB Cloud server
Project youtube_insights created
Database mindsdb_youtube created
Model sentiment_classifier_model created
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Model spam_classifier_model created
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Training the model...
Model text_summarization_model created
Model recommendation_model created
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
```
After that I make a get request using this url:
```
http://127.0.0.1:5000/api/youtube?youtube_video_id=XnSasPR2KJI&limit=5&comment_summary=true&recommendation=true&sentiment=true&spam=true
```
And I got the reponse
```json
{
  "comment_summary": "In the comments, a user shared a link to access some notes related to Python. They mentioned being a class 9th student and expressed their interest in learning coding and starting their journey with Python. However, they mentioned not having a laptop and asked for guidance on how to do programming on an Android phone. Another user asked for instructions on how to install Python and its related software on a Windows computer. Lastly, a user commented on a video, describing it as superb.",
  "recommendation": "Based on the comments you provided, here are some potential topic names that a YouTuber can consider to grow their channel:\n\n1. Learning Python for Beginners\n2. Coding on Android: Programming Languages for Mobile Devices\n3. Installing Python and Related Software on Windows\n4. Python Programming Tutorials for Class 9 Students\n5. Python Programming on Android: Tips and Tricks\n6. Exploring Python: Resources and Study Materials\n7. Python Programming for Students without a Laptop\n8.",
  "sentiments": {
    "negative": 0,
    "neutral": 4,
    "positive": 1
  },
  "spams": 1
}
```

2023-10-26 13:13 UTC, ritwickrajmakhal commented
Again my app's backend and frontend repository are totally separted for the ease of deployment.
You can checkout those repositories:
Backend Repository: https://github.com/ritwickrajmakhal/youtube-insights
Frontend Repository: https://github.com/ritwickrajmakhal/ytinsights

@ZoranPandovski Please tell me if any others changes I have do.

2023-10-27 11:58 UTC, ZoranPandovski approved these changes

2023-10-27 11:58 UTC, merged