Implement pirateweather handler.
mindsdb/mindsdb pull request #7968
Opened 2023-10-21 22:43 UTC by libklein

## Description

Implements a handler for the PirateWeather API. 

Features:
- Historical daily forecast
- Historical hourly forecast

Fixes #7804

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

2023-10-22 09:52 UTC, ZoranPandovski commented
recheckcla

2023-10-22 09:52 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-10-22 09:53 UTC, ZoranPandovski requested changes
Can you please add initial unittests? As a reference check https://github.com/mindsdb/mindsdb/blob/staging/tests/handler_tests/test_binance_handler.py

2023-10-22 10:04 UTC, libklein commented
> Can you please add initial unittests? As a reference check https://github.com/mindsdb/mindsdb/blob/staging/tests/handler_tests/test_binance_handler.py

I already have unit tests set up, but did not want to publish them on Github to avoid compromising my API key. Do you have a suggestion on how to deal with the credentials issue?

2023-10-26 18:20 UTC, libklein commented
I have read the CLA Document and I hereby sign the CLA

2023-10-27 12:50 UTC, ZoranPandovski requested changes
CAn you please share screenshots or short video of working integration?

2023-10-27 12:50 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/pirateweather_handler/README.md
> +The first step is to create a database with the new `github` engine.
Change engine to pirateweather

2023-10-27 19:30 UTC, libklein commented
> CAn you please share screenshots or short video of working integration?

Sure! Here you go:
https://github.com/mindsdb/mindsdb/assets/42714034/f51ef9c2-f48a-4ce7-b714-c84ca7bc3ea1

2023-10-30 11:49 UTC, ZoranPandovski approved these changes

2023-10-30 11:49 UTC, merged