integration nlpcloud handler
mindsdb/mindsdb pull request #8025
Opened 2023-10-24 00:44 UTC by Better-Boy

## Description

NLPCloud handler

Fixes #8024 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

![Screenshot 2023-10-24 at 6 02 05 AM](https://github.com/mindsdb/mindsdb/assets/19553184/5083abbf-ca36-4f5d-84a3-0212f9819621)

![Screenshot 2023-10-24 at 6 09 17 AM](https://github.com/mindsdb/mindsdb/assets/19553184/3ce26013-06b1-4a40-a829-0fe1f6f08f6b)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-11-06 09:03 UTC, paxcema requested changes
Maybe I'm missing something, but why wouldn't this integration be an ML engine instead of an API handler? I.e. inherit `BaseMLEngine` instead.

@ZoranPandovski any thoughts?

2023-11-06 12:37 UTC, Better-Boy commented on mindsdb/integrations/handlers/nlpcloud_handler/README.md
> +## TODO
Done

2023-11-13 13:32 UTC, chandrevdw31 commented
Hey @Better-Boy if your credits are exhausted and you are unable to convert this to ML handler for now, you can convert the PR to a draft so long and wait until you have the credits to work on this contribution

2023-11-13 13:45 UTC, paxcema commented
Indeed, the route @chandrevdw31 is the right option. As it stands, I'm afraid we cannot merge this as an API handler.

2023-11-13 17:13 UTC, Better-Boy commented
Thanks @chandrevdw31 @paxcema . I'll convert this PR to draft.

2023-11-21 03:34 UTC, Better-Boy commented
Closing this PR due to securing another API key is not possible at the moment and nlpcloud hasn't responded to my mails either.

2023-11-21 03:34 UTC, closed without merging