Implemented insert, update and delete queries for carrier service table
mindsdb/mindsdb pull request #8028
Opened 2023-10-24 05:55 UTC by Om-Doiphode

## Description

Please include a summary of the change and the issue it solves. 
Implemented Insert, Update, and Delete queries for the Carrier Service Table. 

Fixes #8016 

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

Insert query: 

![Screenshot from 2023-10-24 10-07-44](https://github.com/mindsdb/mindsdb/assets/83624310/158c76b2-ffa1-459a-bba9-2343d3bd7fe1)

![Screenshot from 2023-10-24 10-08-07](https://github.com/mindsdb/mindsdb/assets/83624310/e757b025-49cf-4c41-9f6a-ed1b2bb06a5d)

Delete query: 

![Screenshot from 2023-10-24 10-14-11](https://github.com/mindsdb/mindsdb/assets/83624310/a1e07779-f0d7-4ad9-9f7f-069c8c4f6c56)

![Screenshot from 2023-10-24 10-15-19](https://github.com/mindsdb/mindsdb/assets/83624310/db1942e5-2413-4eb6-a53b-144a90cf7db3)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-24 05:59 UTC, Om-Doiphode commented
I am facing an issue with the update query. 
![image](https://github.com/mindsdb/mindsdb/assets/83624310/61c435e2-98ff-432c-bd31-8466a65dfec7)
On using the above query I am getting an error. I tried debugging by printing the values for `values_to_update`, `where_conditions`, `carrier_services_df` in the terminal. 
![image](https://github.com/mindsdb/mindsdb/assets/83624310/d4d50220-805c-4cc5-abbd-3f1fff61ff95)
As can be seen in the above image, the entry is present in the table still it gives the above error. Can you please look into this?

2023-10-24 11:11 UTC, ZoranPandovski commented
recheckcla

2023-10-24 11:11 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-10-24 11:12 UTC, ZoranPandovski requested changes
Looks good, let's keep update and delete in this PR and remove the insert. Once you solve the issues you can open another PR with the insert?

2023-10-24 14:49 UTC, Om-Doiphode commented
recheck

2023-10-24 14:53 UTC, Om-Doiphode commented
> Looks good, let's keep update and delete in this PR and remove the insert. Once you solve the issues you can open another PR with the insert?

The insert and delete queries are working fine, there seems to be an issue with the update query. Should I keep only the insert and delete queries then? I will try to solve the issue related to update query and will open a new PR for the update query. Does this work?

2023-10-24 16:32 UTC, someshfengde commented
Hi @ZoranPandovski I'm also facing the same error while updating the database.

2023-10-25 14:07 UTC, supunvindula commented
hi @Om-Doiphode , can you guide me on testing these implementations? Thank you!

2023-10-27 02:23 UTC, Om-Doiphode commented
Hi @ZoranPandovski, is there anything else that needs to be done?

2023-10-27 12:59 UTC, ZoranPandovski requested changes
Also please merge the latest staging before we merge this

2023-10-27 12:59 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
> +        print(f"where_conditions: {where_conditions}")
Please remove the print

2023-10-27 13:57 UTC, Om-Doiphode commented
Hi @ZoranPandovski, I have made the suggested changes, please review. Thanks!

2023-10-28 13:22 UTC, Om-Doiphode commented
Hi @ZoranPandovski, I have merged the latest staging also.

2023-10-31 13:37 UTC, ZoranPandovski approved these changes

2023-10-31 13:37 UTC, merged