Integrated facebook messenger
mindsdb/mindsdb pull request #8067
Opened 2023-10-24 19:34 UTC by Vishalk91-4

## Description

Please include a summary of the change and the issue it solves. 

Fixes #7672

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-31 13:00 UTC, Vishalk91-4 commented
@ZoranPandovski, could you please review this PR for Hacktoberfest

2023-10-31 13:18 UTC, ZoranPandovski requested changes
Thanks. Please make sure you have all of the informations added to the README file and you check all of the steps in the PR checklist

2023-10-31 13:18 UTC, ZoranPandovski commented
recheckcla

2023-10-31 13:19 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-10-31 13:44 UTC, Vishalk91-4 commented
I have read the CLA Document and I hereby sign the CLA

2023-10-31 13:58 UTC, Vishalk91-4 commented
@ZoranPandovski, made the changes

2023-11-01 13:09 UTC, ZoranPandovski requested changes

2023-11-01 13:09 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/facebook_messenger_handler/messenger_handler.py
> +def insert(self, query):
Why this function is outside of the class?

2023-11-01 13:09 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/facebook_messenger_handler/messenger_handler.py
> +                    client = Messager('<access_token>')
Do we need to provide the correct value here?

2023-11-01 13:09 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/facebook_messenger_handler/messenger_handler.py
> +                    send_api = SendApi('<page_access_token>')
Do we need to provide the correct value here?

2023-11-01 13:09 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/facebook_messenger_handler/messenger_handler.py
> +                        QuickReply("Option 1", "PAYLOAD_1"),
Isn't this a hardcoded payload?

2023-11-01 13:09 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/facebook_messenger_handler/messenger_handler.py
> +        for k in ['access_token']:
Shouldn't this be a page_access_token ?

2023-11-01 13:09 UTC, ZoranPandovski commented
@Vishalk91-4 This doesn't work, please check the comments above and make sure you provide screenshots or video of working integrations and include tests

2023-11-15 13:32 UTC, chandrevdw31 commented
Hey @Vishalk91-4 we are coming to a closing with the Hacktoberfest and would like to have this PR merged so that we can gift swag credits to participants. Kindly make above changes and DM me on Slack

2024-01-16 12:39 UTC, closed without merging