Added Support to influxdbv3
mindsdb/mindsdb pull request #8093
Opened 2023-10-25 17:42 UTC by Tanmai2002

## Description

Fix: #7972 

## Type of change
InfluxDB is  Upgraded to Influx DB v3 as Latest. The Current Implementation Should Support V2,V3. InfluxDb v1 is currently archived and legacy. Kindly confirm if we need to persist connection to the same

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [X ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process
![image](https://github.com/mindsdb/mindsdb/assets/40868910/d669a898-7b08-48fc-a89c-33768c9d7e7e)
![image](https://github.com/mindsdb/mindsdb/assets/40868910/2fe24731-824d-40f7-88a5-275b18db6e71)

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-31 13:41 UTC, ZoranPandovski requested changes
Can you please solve the conflicts?

2023-11-02 12:18 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/influxdb_handler/influxdb_handler.py
> +        # if self.is_connected is True:
Can we remove the comments?

2023-11-02 14:12 UTC, bala-ceg commented on mindsdb/integrations/handlers/influxdb_handler/README.md
> +pip install influxdb3-python
please add this Python library to the requirements.txt

2023-11-02 14:35 UTC, Tanmai2002 commented on mindsdb/integrations/handlers/influxdb_handler/influxdb_handler.py
> +        # if self.is_connected is True:
Done

2023-11-03 11:32 UTC, ZoranPandovski approved these changes

2023-11-03 11:32 UTC, merged