World Air Quality Index Handler
mindsdb/mindsdb pull request #8133
Opened 2023-10-26 16:34 UTC by Better-Boy

## Description

World Air Quality Index Handler Implementation

Fixes #8132 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

![Screenshot 2023-10-26 at 9 01 57 PM](https://github.com/mindsdb/mindsdb/assets/19553184/2e77d9c5-31ee-4474-9822-500033fe9a7b)
![Screenshot 2023-10-26 at 9 27 35 PM](https://github.com/mindsdb/mindsdb/assets/19553184/94e20850-db60-489f-a23e-f9b14cbceb15)
![Screenshot 2023-10-26 at 9 35 54 PM](https://github.com/mindsdb/mindsdb/assets/19553184/71095571-6451-445c-accf-8d873e3cce6f)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-11-02 07:20 UTC, MinuraPunchihewa requested changes

2023-11-02 07:40 UTC, Better-Boy commented on mindsdb/integrations/handlers/aqicn_handler/aqicn_tables.py
> +class AQByNetworkStationTable(APITable):
I forgot to register the table with the handler. I added the table and updated the readme.

2023-11-02 07:40 UTC, Better-Boy commented on mindsdb/integrations/handlers/aqicn_handler/README.md
> +~~~~sql
The query doesn't need any columns in where clause as it takes the IP address of the user querying the API.

2023-11-02 07:47 UTC, MinuraPunchihewa requested changes

2023-11-02 07:47 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/aqicn_handler/README.md
> +~~~~sql
@Better-Boy I am not sure what you mean by this. What I was referring to is how, for example, the `city` column is required in the `WHERE` clause to run query the `AQByCityTable`.

2023-11-02 09:35 UTC, Better-Boy commented on mindsdb/integrations/handlers/aqicn_handler/README.md
> +~~~~sql
Ohk, the city column is used to get the air quality index for a given city. For more info - https://aqicn.org/json-api/doc/#api-City_Feed

2023-11-02 09:37 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/aqicn_handler/README.md
> +~~~~sql
Yes, understood. I am just asking for such columns to be mentioned in the README along with the relevant examples.

2023-11-02 12:16 UTC, Better-Boy commented on mindsdb/integrations/handlers/aqicn_handler/README.md
> +~~~~sql
@MinuraPunchihewa Done, updated readme.

2023-11-03 11:12 UTC, MinuraPunchihewa approved these changes

2023-11-06 09:54 UTC, ZoranPandovski approved these changes

2023-11-06 09:54 UTC, merged