together-ai llm inference integration CalHacks 10.0
mindsdb/mindsdb pull request #8180
Opened 2023-10-29 13:33 UTC by jason136

## Description

Integrated the [together ai](https://together.ai) inference api with mindsdb as a model/predictor. 

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-10-29 20:41 UTC, paxcema requested changes
Looking great @jason136! I left a few suggestions before we can merge this, but it'll be great to have an integration with TogetherAI, nice work.

2023-10-29 20:41 UTC, paxcema commented on mindsdb/integrations/handlers/together-ai-handler/together_ai_handler.py
> +    def _get_together_ai_api_key(self, args, strict=True):
There is a common method for this in our utility modules (`mindsdb/integrations/utilities/handler_utils.py`). Please use that instead if possible.

2023-10-29 20:41 UTC, paxcema commented on mindsdb/integrations/handlers/together-ai-handler/together_ai_handler.py
> +        api_key = self._get_together_ai_api_key(args['using'])
You probably want to do `args['using']['api_key']` instead, as `args['using']` is an entire dictionary of parameters.

2023-10-29 20:41 UTC, paxcema commented on mindsdb/integrations/handlers/together-ai-handler/requirements.txt
> +together
I'd suggest pinning the version so that the handler doesn't randomly break if there is a major version release down the line.

2023-10-29 20:41 UTC, paxcema commented on docker/release
> +    pip install --prefer-binary --no-cache-dir together || true && \
I don't think we'll make this a default package just yet, so please remove this.

2023-10-29 20:50 UTC, paxcema commented
Two further things:
- Could you also provide a Loom video showing how this works?
- Could you also write some simple tests that use this integration?

2023-10-30 14:46 UTC, ZoranPandovski commented
recheckcla

2023-10-30 14:46 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-10-30 14:47 UTC, ZoranPandovski requested changes
Thanks. Please solve the pep8 warnings https://github.com/mindsdb/mindsdb/actions/runs/6683740479/job/18160262151?pr=8180#step:5:12

2023-12-12 08:14 UTC, paxcema commented
Hi @jason136, there are some failing checks here related to dependencies and code formatting. Can you check those (details in the github logs) when time allows? Thanks!

2023-12-18 15:27 UTC, paxcema approved these changes
Looks good to me 👍

2023-12-18 15:27 UTC, paxcema commented on mindsdb/integrations/handlers/together_ai_handler/together_ai_handler.py
> +        with ThreadPoolExecutor(max_workers=5) as executor:
Nitpick, mainly for future reference: ideally `max_workers` can be controlled by either the user or mindsdb core.

2023-12-18 15:30 UTC, paxcema commented on mindsdb/integrations/handlers/together_ai_handler/setup.py
> +from setuptools import setup, find_packages
This is failing the automated dep check. I think we don't ask for these `setup.py` files anymore (@ZoranPandovski can you confirm)? So, please remove it and that way the check will pass, too.

2023-12-22 15:00 UTC, paxcema requested changes
Thanks for addressing that @jason136. We're only missing a short test that uses the handler before we can approve 👍

2024-05-03 07:27 UTC, closed without merging