[fix] NeuralForecast - various bugs
mindsdb/mindsdb pull request #8293
Opened 2023-11-07 14:50 UTC by paxcema

## Description

Fixes #7321, #7395, #7768.

Changelog:
- Default to no hyperparam optimization and simple fit instead of crossval for faster model training in vanilla deployments without user config override.
- Change in user defined params: from `train_time` to `n_auto_trials` , `max_steps`, `val_check_steps` and `crossval` for greater control over training duration.
- Fix dependency issues.

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-11-22 11:09 UTC, dusvyat requested changes
After conflicts are resolved this one should be good to go

2023-11-29 12:18 UTC, dusvyat approved these changes

2023-11-29 12:19 UTC, dusvyat commented
@paxcema I can see some integration tests are failing. Not sure if its due to this PR or from other changes that were commited to staging before

2023-11-29 12:41 UTC, paxcema commented
It's actually due to the new releases in type_infer and dataprep_ml... checking now if it is a bug or just something in the test 😛

2023-11-29 15:37 UTC, merged