Added Dependencies for LightFM to Docker Image
mindsdb/mindsdb pull request #8334
Opened 2023-11-10 12:41 UTC by MinuraPunchihewa

## Description

This PR adds the dependencies for the LightFM handler to Docker image.

Fixes https://github.com/mindsdb/mindsdb/issues/8320

## Type of change

- [X] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [X] Download the latest Docker image and connect to LightFM

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [X] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2023-11-13 09:36 UTC, StpMax requested changes

2023-11-13 09:57 UTC, MinuraPunchihewa commented on docker/release
> +    pip install --prefer-binary --no-cache-dir 'lightfm==1.17' 'dataprep_ml>=0.0.15' 'scipy>=1.10.1' 'pydantic~=1.10.8' || true && \
Hey @StpMax,
Sorry, those were mistakes on my part. I have amended the commit.

2023-11-16 12:40 UTC, ea-rus approved these changes

2023-11-16 13:33 UTC, StpMax approved these changes

2023-11-16 13:33 UTC, merged