Using file in unit tests instead of mocking data handler
mindsdb/mindsdb pull request #8336
Opened 2023-11-10 15:07 UTC by ea-rus

## Description

Mocking files might not work in all cases. For example training of model happened in subprocess which not always inhered mocked objects.
Proposal of this PR is to use data from files instead of mocking data handlers.  It adds function save_file in unit test base class and content example how to use it

Fixes #7547

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

2023-11-13 11:40 UTC, dusvyat requested changes
when I run `test_view` in `test_project_structure.py`

It seems I'm still running into the same issue even with mock ml handler being replaced with file load

```
tests/unit/test_project_structure.py:310 (TestProjectStructure.test_view)
self = <tests.unit.test_project_structure.TestProjectStructure object at 0x11fcb0730>

    def test_view(self):
        df = pd.DataFrame([
            {'a': 1, 'b': dt.datetime(2020, 1, 1)},
            {'a': 2, 'b': dt.datetime(2020, 1, 2)},
            {'a': 1, 'b': dt.datetime(2020, 1, 3)},
        ])
        self.save_file('tasks', df)
    
        self.run_sql('''
            create view mindsdb.vtasks (
                select * from files.tasks where a=1
            )
        ''')
    
        # -- create model --
>       self.run_sql(
            '''
                CREATE model mindsdb.task_model
                from mindsdb (select * from vtasks)
                PREDICT a
                using engine='dummy_ml'
            '''
        )

tests/unit/test_project_structure.py:326: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/unit/test_project_structure.py:46: in run_sql
    ret = self.command_executor.execute_command(
mindsdb/utilities/profiler/profiler.py:138: in wrapper
    result = function(*args, **kwargs)
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py:579: in execute_command
    return self.answer_create_predictor(statement)
mindsdb/utilities/functions.py:68: in wrapper
    return func(*args, **kwargs)
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py:1551: in answer_create_predictor
    df = self.session.model_controller.create_model(statement, ml_handler)
mindsdb/interfaces/model/model_controller.py:315: in create_model
    predictor_record = ml_handler.learn(**params)
mindsdb/utilities/profiler/profiler.py:138: in wrapper
    result = function(*args, **kwargs)
mindsdb/integrations/libs/ml_exec_base.py:205: in learn
    task = self.base_ml_executor.apply_async(
mindsdb/integrations/libs/process_cache.py:274: in apply_async
    task = warm_process.apply_async(warm_function, func, payload['context'], payload, dataframe)
mindsdb/integrations/libs/process_cache.py:133: in apply_async
    self.task = self.pool.submit(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <concurrent.futures.process.ProcessPoolExecutor object at 0x2b8344730>
fn = <function warm_function at 0x167847820>
args = (<function learn_process at 0x167847700>, {'company_id': None, 'context_stack': [], 'profiling': {'enabled': False, 'l...myHandler', 'engine': 'dummy_ml', 'integration_id': 9, 'module_path': 'dummy_ml_handler.dummy_ml_handler'}, ...}, None)
kwargs = {}

    def submit(self, fn, /, *args, **kwargs):
        with self._shutdown_lock:
            if self._broken:
>               raise BrokenProcessPool(self._broken)
E               concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py:681: BrokenProcessPool
```

2023-11-14 10:06 UTC, dusvyat commented
Now more tests pass, only the following fail now:

- test_version_managing
- test_last
- test_last_in_job


Trace:


```
FAILED [ 14%]Traceback (most recent call last):
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/integrations/libs/learn_process.py", line 135, in learn_process
    sqlquery = SQLQuery(query, session=sql_session)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 462, in __init__
    self.execute_query()
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 684, in execute_query
    raise e
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 678, in execute_query
    data = self.execute_step(step, steps_data)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 763, in execute_step
    data = self._fetch_dataframe_step(step, steps_data)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 555, in _fetch_dataframe_step
    data, columns_info = dn.query(
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/utilities/profiler/profiler.py", line 136, in wrapper
    result = function(*args, **kwargs)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py", line 153, in query
    raise Exception(f'Error in {self.integration_name}: {result.error_message}')
Exception: Error in pg: relation "tasks" does not exist
LINE 1: select * from tasks
                      ^

ERROR:dummy:[Chromadb-handler] pysqlite3 is not installed, this is not a problem for local usage
ERROR:dummy:Error running query: select * from tasks on None!

tests/unit/test_project_structure.py:63 (TestProjectStructure.test_version_managing)
self = <tests.unit.test_project_structure.TestProjectStructure object at 0x144ddf4c0>
data_handler = <MagicMock name='Handler' id='6063238976'>

    @patch('mindsdb.integrations.handlers.postgres_handler.Handler')
    def test_version_managing(self, data_handler):
        # set up
    
        df = pd.DataFrame([
            {'a': 1, 'b': dt.datetime(2020, 1, 1)},
            {'a': 2, 'b': dt.datetime(2020, 1, 2)},
            {'a': 1, 'b': dt.datetime(2020, 1, 3)},
        ])
        self.set_handler(data_handler, name='pg', tables={'tasks': df})
    
        # ================= retrain cycles =====================
    
        # create folder
        self.run_sql('create database proj')
    
        # -- create model --
        ret = self.run_sql(
            '''
                CREATE model proj.task_model
                from pg (select * from tasks)
                PREDICT a
                using engine='dummy_ml',
                tag = 'first',
                join_learn_process=true
            '''
        )
        assert ret['NAME'][0] == 'task_model'
        assert ret['ENGINE'][0] == 'dummy_ml'
>       self.wait_predictor('proj', 'task_model')

tests/unit/test_project_structure.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.unit.test_project_structure.TestProjectStructure object at 0x144ddf4c0>
project = 'proj', name = 'task_model', filter = None

    def wait_predictor(self, project, name, filter=None):
        # wait
        done = False
        for attempt in range(200):
            sql = f"select * from {project}.models_versions where name='{name}'"
            if filter is not None:
                for k, v in filter.items():
                    sql += f" and {k}='{v}'"
            ret = self.run_sql(sql)
            if not ret.empty:
                if ret['STATUS'][0] == 'complete':
                    done = True
                    break
                elif ret['STATUS'][0] == 'error':
                    break
            time.sleep(0.5)
        if not done:
>           raise RuntimeError("predictor didn't created")
E           RuntimeError: predictor didn't created

tests/unit/test_project_structure.py:42: RuntimeError
PASSED [ 28%]PASSED [ 42%]PASSED [ 57%]PASSED [ 71%]FAILED [ 85%]Traceback (most recent call last):
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/integrations/libs/learn_process.py", line 135, in learn_process
    sqlquery = SQLQuery(query, session=sql_session)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 462, in __init__
    self.execute_query()
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 684, in execute_query
    raise e
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 678, in execute_query
    data = self.execute_step(step, steps_data)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 763, in execute_step
    data = self._fetch_dataframe_step(step, steps_data)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 555, in _fetch_dataframe_step
    data, columns_info = dn.query(
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/utilities/profiler/profiler.py", line 136, in wrapper
    result = function(*args, **kwargs)
  File "/Users/d/PycharmProjects/mindsdb/mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py", line 153, in query
    raise Exception(f'Error in {self.integration_name}: {result.error_message}')
Exception: Error in pg: relation "tasks" does not exist
LINE 1: select * from tasks
                      ^

ERROR:dummy:Error running query: select * from tasks on None!

tests/unit/test_project_structure.py:496 (TestProjectStructure.test_last)
self = <tests.unit.test_project_structure.TestProjectStructure object at 0x144ddfb80>
data_handler = <MagicMock name='Handler' id='6201312784'>

    @patch('mindsdb.integrations.handlers.postgres_handler.Handler')
    def test_last(self, data_handler):
        df = pd.DataFrame([
            {'a': 1, 'b': 'a'},
            {'a': 2, 'b': 'b'},
            {'a': 3, 'b': 'c'},
        ])
        self.set_handler(data_handler, name='pg', tables={'tasks': df})
    
        # -- create model --
        self.run_sql(
            '''
                CREATE model task_model
                from pg (select * from tasks)
                PREDICT a
                using engine='dummy_ml'
            '''
        )
    
        # --- check web editor  ---
        ret = self.run_sql('''
            select * from pg.tasks where a>last
         ''')
        # first call is empty
        assert len(ret) == 0
    
        # add rows to dataframe
        df.loc[len(df.index)] = [4, 'd']  # should be tracked
        df.loc[len(df.index)] = [0, 'z']  # not tracked
    
        ret = self.run_sql('''
            select * from pg.tasks where a>last
        ''')
    
        # second call content one new line
        assert len(ret) == 1
        assert ret.a[0] == 4
    
        # --- TEST view ---
    
        # view without target
        with pytest.raises(Exception) as exc_info:
            self.run_sql('''
                create view v1 (
                    select b from pg.tasks where a>last
                )
            ''')
        assert 'should be in query target' in str(exc_info.value)
    
        # view with target
        self.run_sql('''
            create view v1 (
                select * from pg.tasks where a>last
            )
        ''')
    
        ret = self.run_sql('''
          select * from v1
        ''')
        # first call is empty
        assert len(ret) == 0
    
        # add row to dataframe
        df.loc[len(df.index)] = [5, 'a']
    
        ret = self.run_sql('''
            select * from v1
        ''')
    
        # second call content one new line
        assert len(ret) == 1
        assert ret.a[0] == 5
    
        # add row to dataframe
        df.loc[len(df.index)] = [6, 'a']
    
        # use model
>       ret = self.run_s [...]

2023-11-14 11:24 UTC, ea-rus commented
Fixed import of dummy_ml_handler in subprocess
this example should work now
```
env PYTHONPATH=./  pytest tests/unit/test_project_structure.py -k test_view
```

2023-11-14 12:05 UTC, dusvyat approved these changes

2023-11-14 13:36 UTC, merged