[Integration] Google Cloud Storage Integration
mindsdb/mindsdb pull request #8520
Opened 2023-12-17 13:12 UTC by vikiluk

## Description

Google Cloud Storage Handler implementation.

Fixes #7695

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]  Test Location: mindsdb/integrations/handlers/google_cloud_storage_handler/tests/test_google_cloud_storage_handler.py
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

2023-12-18 16:19 UTC, ZoranPandovski commented
recheckcla

2023-12-18 16:19 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2023-12-18 16:22 UTC, VikiLuk commented
I have read the CLA Document and I hereby sign the CLA

2023-12-21 07:48 UTC, MinuraPunchihewa requested changes
Hey @VikiLuk,
This is great work!
Can we please do the following so that we can merge this,
1. Let's give users the ability to provide the path to their service account keys (as you've already done) and also the option to provide the JSON content within the keys file, when connecting to their cloud storage. We can have two connection parameters called `service_account_keys` and `service_account_json` for this purpose. You can refer the Google BigQuery handler to implement this; here is the [code](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/bigquery_handler) and the [documentation](https://docs.mindsdb.com/integrations/data-integrations/google-bigquery).
2. Let's remove the `call_application_api()` function from the handler and move the individual methods for performing operations on bucket resources to the `APITable` implementation (`GoogleCloudStorageBucketsTable`). This logic, in my opinion, belongs there.
3. Please provide either screenshots or a short video of your integration working once the above changes have been made.

2025-07-14 12:11 UTC, martyna-mindsdb commented
Closing this PR due to inactivity.

2025-07-14 12:11 UTC, closed without merging