youtube documentation update
mindsdb/mindsdb pull request #8682
Opened 2024-01-24 23:28 UTC by QuantumPlumber

## Description

Documentation update to reflect the YouTube handler Readme.md. I assume that the read me is up to date.

Fixes #8667 

## Type of change
- [ x ] 📄 This change requires a documentation update

## Checklist:

- [ x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ x ] I have appropriately commented on my code, especially in complex areas.
- [ x ] Necessary documentation updates are either made or tracked in issues.
- [ x ] Relevant unit and integration tests are updated or added.

2024-01-25 15:19 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +## Install the Handler
Throughout the app integration docs, we use sections "Connection" and "Usage".  Let's keep it consistent.
So let's change it back to Connection.

2024-01-25 15:22 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +  "YouTube_api_token": "<your-YouTube-api-key-token>"
Same as above - this should be `youtube_api_token`.

2024-01-25 15:23 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +~~~~sql
In the MDX format, we use triple backticks, so please change it back throughout this doc page.

2024-01-25 16:21 UTC, MinuraPunchihewa requested changes
Hey Ave!
Thank you for this. There is a small update that we need to make to the Connection section, specifically to the parameters that are used to initialize the handler. It is now possible to pass OAuth credentials (generated through the GCP console) as a URL, file path and even upload it directly (when using the form).

P.S: You have the coolest username!

2024-01-25 17:01 UTC, martyna-mindsdb commented
Hey @MinuraPunchihewa @QuantumPlumber 
I'm waiting until the credentials_file param is supported, and also, until OAuth2 (credentials_url) is deployed.
Then, I plan to update yt docs to include OAuth2.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +## Usage
Please remove this "## Usage" from this line.

The Connection section ends after the CREATE DATABASE statement. And there is already the Usage section.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +~~~~sql
Please change it back to triple backticks as above.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +~~~~sql
Please change it back to triple backticks as above.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +~~~~sql
Please change it back to triple backticks as above.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +~~~~sql
Please change it back to triple backticks as above.

2024-01-26 11:24 UTC, martyna-mindsdb commented on docs/integrations/app-integrations/youtube.mdx
> +The first step is to create a database with the new ```youtube``` engine using the following command:
The inline code uses single backticks. So it should be "...with the new \`youtube` engine..."

2024-01-26 17:36 UTC, martyna-mindsdb approved these changes

2024-01-30 06:28 UTC, MinuraPunchihewa approved these changes

2024-01-30 06:28 UTC, merged