Gemini updated
mindsdb/mindsdb pull request #8701
Opened 2024-01-27 09:41 UTC by parthiv11

## Description

Please include a summary of the change and the issue it solves. 

Fixes #8699 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

https://github.com/mindsdb/mindsdb/assets/75653580/fe1af932-dcc5-4819-9d7c-912ab8bb8f1a

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-02-02 01:19 UTC, torrmal commented
amazing @paxcema what do you think?

2024-02-06 05:41 UTC, parthiv11 commented
https://github.com/mindsdb/mindsdb/assets/75653580/bfd1c614-ffa4-438a-9faa-6711d3ea41df

2024-02-06 05:47 UTC, parthiv11 commented
@paxcema now its support's Json extraction also

2024-02-08 14:18 UTC, paxcema requested changes
Generally looks good. However, there is some code duplication from the OpenAI handler. That's alright for the sake of updating this integration, but could you please:

> add a disclaimer at the top of every duplicated code so that we know to refactor it, and open an issue so that we can work on it at a later stage


**Ideally**, you'd be able to follow-up on this, either on this PR or on a subsequent one.

Refactoring any duplicated snippets into common utilities for all handlers to leverage is an important task we have, to keep the codebase healthy. It is also nice to see that common patterns do emerge from LLM integrations 😄

2024-02-08 14:41 UTC, parthiv11 commented on mindsdb/integrations/handlers/google_gemini_handler/requirements.txt
> +Pillow==10.1.0
no i think it not necessary, therefore i am removing it

2024-02-17 13:23 UTC, parthiv11 commented
@paxcema sorry for being so late, please check updated code.

2024-02-17 13:23 UTC, parthiv11 commented
i can open a new PR for refactor, if it sounds good to you

2024-03-04 04:56 UTC, parthiv11 commented
@paxcema you can merge this PR

2024-03-11 14:07 UTC, paxcema commented
@parthiv11 copying comment from #8861 here, for reference. Sorry about the delay:

> we'll kindly ask that you please work on this one in the same branch and pull request (https://github.com/mindsdb/mindsdb/pull/8701), do let us know when it's ready for review, thanks for your contribution!!

In other words, please add the refactor to this PR. We'd rather merge this integration from a single PR that contains all needed for great quality and UX.

2024-05-29 05:16 UTC, parthiv11 commented
@paxcema ??

2024-06-12 17:05 UTC, paxcema approved these changes
Changes look OK. Tagging @ZoranPandovski for visibility.

@parthiv11 please merge `main` into this, and I will get the workflows running to check tests in the CI. Once that is done, we can merge. Thanks for your patience!

2024-06-12 18:00 UTC, parthiv11 commented
thank you @paxcema 
@ZoranPandovski  done

2024-06-13 22:21 UTC, paxcema commented
@parthiv11 static code check is failing, try `flake8 ./` in your handler folder to spot all the relevant lines that must be fixed

2024-06-28 09:43 UTC, parthiv11 commented
@paxcema and @ZoranPandovski I check workflows and it worked ed, please verify it

2024-07-04 03:55 UTC, parthiv11 commented
@ZoranPandovski  i think is PR is done, please checkout it

2024-07-09 09:21 UTC, merged