Added File Path and URL Support to the Vertex AI Integration
mindsdb/mindsdb pull request #9007
Opened 2024-03-29 12:09 UTC by MinuraPunchihewa

## Description

This PR adds the ability to pass service account keys as either a file path or URL when instantiating a Vertex AI ML engine. This is achieved using the `service_account_key_file` and `service_account_key_url` parameters respectively. The existing `service_account` parameter has also been renamed to `service_account_key_json`.

To implement the above functionality a new utility class called `GoogleServiceAccountOAuth2Manager` has been added. The existing `GoogleOAuth2Manager` has been renamed to `GoogleUserOAuth2Manager` for clarity.

Fixes https://github.com/mindsdb/mindsdb/issues/8961

## Type of change

- [X] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-04-02 10:04 UTC, ZoranPandovski requested changes
Awesome, please check the few comments

2024-04-02 10:58 UTC, MinuraPunchihewa commented
Hey @ZoranPandovski,
I have made the requested changes.

2024-04-02 12:29 UTC, ZoranPandovski approved these changes

2024-04-04 13:07 UTC, ea-rus commented on mindsdb/integrations/handlers/vertex_handler/vertex_client.py
> +    def __init__(self, credentials_url, credentials_file, credentials_json, args_json):
looks like all 3 methods to pass credentials required (should be passed all of them)
but in reality only one
maybe to add default values them?

2024-04-04 13:08 UTC, ea-rus approved these changes
The rest looks good

2024-04-04 15:57 UTC, merged