openapi docs for agents/skills/chatbots
mindsdb/mindsdb pull request #9113
Opened 2024-04-22 16:54 UTC by martyna-mindsdb

## Description

openapi docs for agents/skills/chatbots

Fixes #8851 

## Type of change

- [ ] 📄 This change is a documentation update

2024-04-23 13:01 UTC, ZoranPandovski requested changes

2024-04-23 13:01 UTC, ZoranPandovski commented on docs/openapi.yml
> +        - ApiKeyAuth: []
We can remove this for now

2024-04-23 13:08 UTC, martyna-mindsdb commented on docs/openapi.yml
> +        - ApiKeyAuth: []
removed it from all

2024-04-24 14:37 UTC, ZoranPandovski approved these changes

2024-04-24 14:37 UTC, merged