Update Langchain Community Chat Model Name Params
mindsdb/mindsdb pull request #9237
Opened 2024-05-21 17:03 UTC by tmichaeldb

## Description

`llm_model_name` is no longer used for `ChatOpenAI`, `ChatAnyScale`, etc Langchain classes. This PR uses the correct, updated config params when defining model name.

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-05-22 12:31 UTC, ZoranPandovski requested changes

2024-05-22 12:31 UTC, ZoranPandovski commented on requirements/requirements.txt
> -pydantic >= 2.0.3
Hey @tmichaeldb just a quick check here, that this doesn't affect other integrations that are using Pydantic? Are there any other required changes when upgrading? The last time this broke few integrations with depricated params provided?

2024-05-22 21:45 UTC, hamishfagg commented
@tmichaeldb the pydantic upgrade looks fine as long as our tests pass. I would just pass an eye over their release notes between the two versions to check nothing major has changed.

But for the `llm_model_name` rename - I changed it from `model_name` to `llm_model_name` recently because pydantic protects everything prefixed with `model_` and it was throwing errors. I didn't realise that name was for langchain though.

So im not sure how to work around that. Here's the docs for the protected namespace in pydantic:
https://docs.pydantic.dev/latest/api/config/#protected-namespaces

2024-05-24 15:27 UTC, ZoranPandovski approved these changes

2024-05-24 15:33 UTC, merged