Mindsdb optimizations
mindsdb/mindsdb pull request #9243
Opened 2024-05-24 11:16 UTC by ea-rus

## Description

Please include a summary of the change and the issue it solves. 

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-06-04 11:21 UTC, StpMax requested changes

2024-06-04 11:21 UTC, StpMax commented on mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
> +                with cur.copy(f'copy {table_name} from STDIN  WITH CSV') as copy:
what if columns order is not the same?

2024-06-05 15:49 UTC, ea-rus commented on mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
> +                with cur.copy(f'copy {table_name} from STDIN  WITH CSV') as copy:
thanks! fixed

2024-06-06 09:42 UTC, StpMax approved these changes

2024-06-06 11:01 UTC, merged