Dependencies: Migrate from `crate[sqlalchemy]` to `sqlalchemy-cratedb`
mindsdb/mindsdb pull request #9345
Opened 2024-06-13 21:00 UTC by amotl

## About
The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch intends to accompany the migration.

## Details
The new canonical package for the SQLAlchemy CrateDB dialect on PyPI is:

> https://pypi.org/project/sqlalchemy-cratedb/

/cc @hammerhead, @hlcianfagna

2024-06-14 11:53 UTC, ZoranPandovski approved these changes

2024-06-14 11:53 UTC, ZoranPandovski commented
recheckcla

2024-06-14 11:53 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-06-14 13:01 UTC, amotl commented
I have read the CLA Document and I hereby sign the CLA

recheck

2024-06-14 13:02 UTC, amotl commented
I have read the CLA Document and I hereby sign the CLA

2024-06-14 13:02 UTC, amotl commented
recheck

2024-07-22 05:58 UTC, MinuraPunchihewa requested changes
Hey @amotl,
Since we are [also using the Create DBAPI](https://github.com/mindsdb/mindsdb/blob/27b6012985081ddccda6bcc8a5368643d38cff91/mindsdb/integrations/handlers/crate_handler/crate_handler.py#L17), we will need to include it in the requirements.txt file. We can, of course, omit the `sqlalchemy` extra now.

2024-07-22 15:51 UTC, amotl commented
Hi Minura,

the `crate` package is a dependency of `sqlalchemy-cratedb`, so you can omit it from the dependencies, and still import it. `sqlalchemy-cratedb` will take care of pulling in the right version. Currently, that is [crate==1.0.0.dev0](https://pypi.org/project/crate/1.0.0.dev0/), but that will converge to `1.0.0` on the next iteration.

With kind regards,
Andreas.

2024-07-22 20:04 UTC, amotl commented
Hi. I've updated the patch like you suggested. I've the build will pick up [crate==1.0.0.dev0](https://pypi.org/project/crate/1.0.0.dev0/), it will be good to go. Otherwise, probably not.

2024-07-23 05:24 UTC, MinuraPunchihewa commented
Thank you, @amotl! Sorry for the trouble, but could you please sync your fork with the main branch? There is another CI check that is failing. I believe this is an issue on our end, but I remember that it was fixed frequently. I think syncing your branch with our main should do the trick.

2024-07-23 11:13 UTC, amotl commented
Hi Minura,

I did a rebase yesterday whle already adjusting the patch according to your suggestions. Right now, I've used the "Rebase branch" button on GitHub once more.

With kind regards,
Andreas.

2024-07-23 14:34 UTC, MinuraPunchihewa commented
Hey @hamishfagg,
Do you have any idea why this is still failing? I believe we added a check to ensure that this does not forked repos, if I am not mistaken?

2024-07-23 15:24 UTC, amotl commented
I also think it must be something in `mindsdb/github-actions`, that trips because the PR is coming from the fork of an external contributor.

Feel free to use this as a blueprint example to eventually improve your shared actions on this detail of being more welcoming to external contributors.

If you see some room for improvements, please just go ahead and refresh (rebase) this page at your disposal.

2024-07-25 04:20 UTC, hamishfagg commented
Hey guys,
So we have been trying to think of a nice way to allow actions to run on forks for a while, but it's very tricky security-wise.
I've just made a change that will let things pass now, so long as we don't need to deploy it to a dev environment to test. 
Luckily this is a simple PR  so I think we can get away with not doing that?

Anyway this has prodded me to try get this sorted again, sorry for the inconvenience.

2024-07-25 05:12 UTC, MinuraPunchihewa commented
Thanks, @hamishfagg. Yes, it won't be necessary to deploy it to a test environment right now. I will merge the PR.

2024-07-25 05:12 UTC, MinuraPunchihewa approved these changes

2024-07-25 05:12 UTC, merged