Serpstack api integration
mindsdb/mindsdb pull request #9381
Opened 2024-06-20 16:39 UTC by andersooi

## Description

Created an integration for Serpstack API

Fixes #5641 

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Please refer to the loom recording attached below
 - [x]   Verification Steps: Implemented the integration and documented the process in a README.md file

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

[https://www.loom.com/share/3bcaf48ee84e4359b5e95e7e5a9a7f85?sid=b8f0169d-0adc-47bd-a2f8-7d6aa86c885f](Loom Recording)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-06-28 10:42 UTC, ZoranPandovski commented
recheckcla

2024-06-28 10:42 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-07-07 15:42 UTC, andersooi commented
I have read the CLA Document and I hereby sign the CLA

2024-07-19 00:35 UTC, andersooi commented
Hi @ZoranPandovski, there seems to be the following test that is failing but am unsure of what to do on my end to resolve it. If possible, could you give me some guidance on how to go about resolving it?

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/995bf4f5-fba4-4102-bbe6-5cce3857aa4d">

2024-07-22 10:49 UTC, ZoranPandovski requested changes
Thanks @andersooi , don't worry about that failing action. I've added few minor comments

2024-07-22 10:49 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/serpstack_handler/serpstack_tables.py
> +        api_response = requests.get(self.handler.base_url, params=params)
Can we check for exceptions here?

2024-07-22 10:49 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/serpstack_handler/serpstack_tables.py
> +    def filter_columns(self, result: pd.DataFrame, query: ast.Select = None):
Can we add a comments about what this does?

2024-07-22 10:49 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/serpstack_handler/serpstack_handler.py
> +            self.connect()
Maybe we don't need to call connect again but simply make a health-check request to serpstack?

2024-07-23 15:04 UTC, andersooi commented
Hi @ZoranPandovski I have made some changes based on the comments you gave. Do let me know if I need to make any additional edits or clarifications

2024-07-29 11:35 UTC, ZoranPandovski commented
Great, just two flake warnings and this is good to merge https://github.com/mindsdb/mindsdb/actions/runs/10061406316/job/28044774189?pr=9381#step:6:75

2024-08-02 10:17 UTC, MinuraPunchihewa requested changes
Hey @andersooi,
Thank you very much for your contribution. This looks great!
There is just a couple of things I wanted to point out,
1. The connect() method of our API handlers is typically expected to return an instance of a client (package) that will allow us to interact with the API in question. Not an instance of StatusResponse (although this is incorrectly used as a type hint in some of our handlers). [Here](https://github.com/mindsdb/mindsdb/blob/bc102f4011837d289bca43d7978717f408818e6b/mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py#L55) is a good example of a correct implementation. Now, I understand that since you are using `requests` here, there is no client instance as such that can be returned. Therefore, you can choose to return something else; for instance the `base_url` and then you can use this within your `BaseResultsTable` like `base_url = self.handler.connect()`. It is completely up to you how you want to handle this, but in essence, what needs to be done is to remove the `StatusResponse` logic from `connect()`.
2. The `check_connection()` method is used to determine if a valid connection with the API can be established using the credentials that have been provided. I see that you are checking the health status of the API in this method, however, this does not check the validity of the API key provided. Instead what you can do is to call `connect()` within `check_connection()` and determine the validity of the connection from there. This method does indeed require a StatusResponse object to be returned and therefore, you can use error handling with the call to `connect()` in order to return the required response. [Here](https://github.com/mindsdb/mindsdb/blob/bc102f4011837d289bca43d7978717f408818e6b/mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py#L88) again, is an example of a more suitable implementation of this.

Finally, if you could add a couple of screenshots of this handler that would be amazing.

2024-08-10 18:58 UTC, andersooi commented
Hi @MinuraPunchihewa I have made some changes based on your comments. Do let me know if there are any areas that require further edits.

I have attached a link to the loom recording of the integration usage in the pull request's description, [here](https://www.loom.com/share/3bcaf48ee84e4359b5e95e7e5a9a7f85?sid=b8f0169d-0adc-47bd-a2f8-7d6aa86c885f) it is for easier access.

Attached below is also a screenshot of the integration in use.

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/a0b167f1-f7d1-4d62-be2f-29fc8a2f1029">

Thank you.

2024-08-14 11:31 UTC, MinuraPunchihewa approved these changes
This looks good to me now! Thanks, @andersooi!

2024-09-30 12:01 UTC, ZoranPandovski requested changes
@andersooi THank you, can you please just merge master so we avoid failing tests?

2024-09-30 12:04 UTC, andersooi commented
@ZoranPandovski done!

2024-10-11 09:20 UTC, merged