Update sdk & minor changes to connection of cluster
mindsdb/mindsdb pull request #9703
Opened 2024-09-09 11:55 UTC by prajwal-pai77

## Description

- Updates the python couchbase sdk to latest version.
- Updated the connection to couchbase by using connection_string.
- Updated relevant docs.

Fixes #9702 

## Type of change

(Please delete options that are not relevant)

- 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [X] Necessary documentation updates are either made or tracked in issues.
- [X] Relevant unit and integration tests are updated or added.

2024-09-10 05:26 UTC, MinuraPunchihewa reviewed
Hey @prajwal-pai77,
Thank you for this PR.
Will the protocol for the connection string always be `couchbase://`? In that case, I think we would prefer the `host` parameter; we can then build the connection string in the connection logic. Even if this is not so, I think we can maybe use an optional `protocol` parameter along with `host`. It can default to the most commonly used protocol (e.g. `couchbase`). Our [Clickhouse integration](https://docs.mindsdb.com/integrations/data-integrations/clickhouse) follows a similar pattern.

Can you also please confirm that you do not run into any dependency conflicts after updating the version of the SDK?

Finally, it looks like you've got a small lint issue that our CI has detected.

2024-09-10 06:28 UTC, prajwal-pai77 commented
Hey @MinuraPunchihewa 
Thanks for taking a look.
The connection string will not always be couchbase://, When using couchbase capella, the `connection_string` can be found out in the connect tab, and it will contain the couchbases://, so just specifying that should be enough. I have mentioned it in the doc:
```the `connection_string` can be found out when you navigate under the Connect tab.```
When running locally, couchbase:// is sufficient as shown in the example.

I have tested the couchbase_handler.py file after upgrading the sdk, please let me know if i need to test anything else, so i don't run into dependency conflicts.

How can i fix this lint issue? Is there anthing i can refer to?

2024-10-03 05:10 UTC, MinuraPunchihewa requested changes
I left a few minor comments to fix the grammar in the docs.

In order to fix the CI, simply remove the unused import of `urllib.parse.urlparse` in `couchbase_handler.py.`

2024-10-03 05:10 UTC, MinuraPunchihewa commented on docs/integrations/data-integrations/couchbase.mdx
> +Note: The connection string expects the couchbases:// or couchbase:// part.
Let's make this,
Note: The connection string expects either the couchbases:// or couchbase:// protocol.

Please make the same change in the README.

2024-10-03 05:10 UTC, MinuraPunchihewa commented on docs/integrations/data-integrations/couchbase.mdx
> +If you are using Couchbase Capella, the `connection_string` can be found out when you navigate under the Connect tab.
Let's make this:
If you are using Couchbase Capella, you can find the connection_string under the Connect tab.

Please make the same change in the README.

2024-10-03 05:10 UTC, MinuraPunchihewa commented on docs/integrations/data-integrations/couchbase.mdx
> +* `connection_string`: the Connection string to specify the cluster endpoint
Let's make this,
the connection string for the endpoint of the Couchbase server

Please make the same change in the README.

2024-10-03 08:33 UTC, MinuraPunchihewa approved these changes
LGTM!

2024-10-03 08:34 UTC, merged

2024-10-03 11:27 UTC, ZoranPandovski commented
recheckcla

2024-10-03 11:28 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-10-03 11:28 UTC, ZoranPandovski commented
@prajwal-pai77 Can you please sign the CLA?

2024-10-03 19:38 UTC, prajwal-pai77 commented
I have read the CLA Document and I hereby sign the CLA