Changes in ecryption functions
mindsdb/mindsdb pull request #9705
Opened 2024-09-10 08:32 UTC by ea-rus

## Description

Changes in behaviour of  ecryption functions
- encrypted string marked with prefix
- encrypt, encrypt_object  
  - if encryption is enabled - return encrypted string
  - else return the input 
- decrypt return the same string if input is not encrypted

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-10-11 10:06 UTC, StpMax requested changes

2024-10-11 10:06 UTC, StpMax commented on mindsdb/utilities/security.py
> +        "MDB_ENC": _encrypt_v1(message_bytes)
should it be `ENCRYPT_JSON_KEY`?

2024-10-11 14:48 UTC, ea-rus commented on mindsdb/utilities/security.py
> +        "MDB_ENC": _encrypt_v1(message_bytes)
yes, fixed

2025-07-14 12:27 UTC, martyna-mindsdb commented
@ea-rus 
Is this still valid?

2025-07-14 12:34 UTC, closed without merging