LiteLLM 1.44.8
mindsdb/mindsdb pull request #9781
Opened 2024-10-02 10:58 UTC by anantrajjj

### **Description:-**
The project is currently using an older version of LiteLLM. The goal of this issue is to upgrade the LiteLLM package to version 1.44.8.

Updated requirements.txt and setup.py to use LiteLLM==1.44.8.
Tested the project to verify functionality after the upgrade.
Fixes https://github.com/mindsdb/mindsdb/issues/9776

### **Type of change**
 ⚡ New feature (non-breaking change which adds functionality)
 version update to 1.44.8
Verification Process
To ensure the changes are working as expected:

 to validate run :- pip show LiteLLM
Additional Media:
![image](https://github.com/user-attachments/assets/34fb1807-2b89-419a-b5a1-dfaaa7c1c95f)##tested and demonstrated the updation of LiteLLM

2024-10-03 10:04 UTC, ZoranPandovski requested changes

2024-10-03 10:04 UTC, ZoranPandovski commented on pyproject.toml
> +[tool.poetry.dependencies]
We don't need the `pyprojec.toml` please remove it

2024-10-03 10:06 UTC, ZoranPandovski commented
recheckcla

2024-10-03 10:06 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-10-08 12:21 UTC, ZoranPandovski approved these changes

2024-10-08 12:21 UTC, merged