Upgrading and migrating CKAN Handler
mindsdb/mindsdb pull request #9788
Opened 2024-10-03 12:16 UTC by tino097

## Description

Please include a summary of the change and the issue it solves. 

Fixes #9785 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-10-10 10:46 UTC, ZoranPandovski requested changes
Awesome, I've added few minor comments. Also please check the flake8 warnings https://github.com/mindsdb/mindsdb/actions/runs/11200239456/job/31346903311?pr=9788#step:6:115

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/__init__.py
>  icon_path = 'icon.png'
We are missing an CKAN inon in png format

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/__init__.py
>  icon_path = 'icon.png'
Please push that

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +        return HandlerResponse(RESPONSE_TYPE.TABLE, packages)
We should return the dataframe here since the HandlerResponse will be handled by CkanHandler

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +    def list(self, conditions=None, limit=1000):
By default, this will always work with 1000 rows, right? if so, we may add in the README

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +        return HandlerResponse(RESPONSE_TYPE.TABLE, resources)
Let's return dataframe here too

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +        return HandlerResponse(RESPONSE_TYPE.TABLE, data)
Same as above, we may  return df

2024-10-10 10:46 UTC, ZoranPandovski commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +            self.connection = RemoteCKAN(url, apikey=api_key)
Is this enough for checking the connection, or do we need to somehow execute some simpler action?

2024-10-11 09:48 UTC, MinuraPunchihewa requested changes

2024-10-11 09:48 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/ckan_handler/README.md
> +pip install mindsdb
Hey @tino097,
We don't recommend installing MindsDB via PyPI anymore; can you please update this by instructing users to install it via Docker or Docker Desktop, please? [Here](https://github.com/mindsdb/mindsdb/tree/main/mindsdb/integrations/handlers/hana_handler) is an example.

2024-10-11 09:48 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/ckan_handler/ckan_handler.py
> +    def query(self, query: ast.Select) -> HandlerResponse:
This method implementation is not required. The `APIHandler` interface already handles this. Let's remove it.

2024-10-11 10:14 UTC, tino097 commented
Only issue that i've noticed is that the if i use UI to create the connection with steps 
* Add new datasource
* Choose CKAN handler
* Fill the URL and/or API Token

 Those values never get passed to the handler and `connection_data ` is empty

2024-10-14 08:52 UTC, MinuraPunchihewa approved these changes
Looks fine to me now!
@tino097 If you can, just remove the commented query() method. It won't be required.

2024-10-14 13:12 UTC, ZoranPandovski approved these changes

2024-10-14 13:12 UTC, merged