added authentication for private hf models
mindsdb/mindsdb pull request #9845
Opened 2024-10-14 10:28 UTC by the-dg04

## Description

Added authentication for private hf models by adding an optional `use_auth_token` param while creating a new hf model using `CREATE MODEL` + updated docs for the same.

Fixes #9842 

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-10-14 10:42 UTC, ZoranPandovski approved these changes

2024-10-14 10:42 UTC, ZoranPandovski commented
recheckcla

2024-10-14 10:43 UTC, mindsdbadmin commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-10-14 10:57 UTC, the-dg04 commented
I have read the CLA Document and I hereby sign the CLA

2024-10-15 04:24 UTC, MinuraPunchihewa requested changes
Hi @the-dg04,
According to this [post](https://discuss.huggingface.co/t/the-use-auth-token-argument-is-deprecated-and-will-be-removed-in-v5-of-transformers/53943) in the HuggingFace forum, the `use_auth_token` parameter is going to be depreciated in the near future. Can we please use the `token` parameter instead?

Furthermore, please do the following:
1. Post a screenshot or video of successfully executing queries via the MinsdsDB Editor after your changes.
2. Add these changes to the documentation for the integration in addition to the README.

2024-10-15 04:24 UTC, MinuraPunchihewa commented on mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
> +                pipeline = transformers.pipeline(task=args['task_proper'], model=model_name,use_auth_token=use_auth_token)
Let's not do this. Let's only accept it as a boolean argument.

2024-11-12 13:22 UTC, ZoranPandovski commented
Hey @the-dg04  we haven't heard back regarding this PR . Just a friendly reminder that if there's no response, we may need to close this PR to keep the repository organized. If you're still working on this or would like to continue, please let us know! Even if we close it, you're always welcome to comment here, and we can reopen it at any time

2024-11-12 13:22 UTC, closed without merging