Updated command_executor.py  for handling authorization required message from youtube handler
mindsdb/mindsdb pull request #9934
Opened 2024-10-18 13:30 UTC by Sekhar-Kumar-Dash

## Description

this PR adds proper handling  of authorization required message from youtube handler

Fixes #9876

## Type of change
- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
![{764B22C0-0D8F-4F5A-9B21-061CA3AD4B8E}](https://github.com/user-attachments/assets/b26ebd9f-597d-4bb1-8e2a-d76dc79e9d82)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

2024-10-18 13:33 UTC, Sekhar-Kumar-Dash commented
@martyna-mindsdb please have a look

2024-10-22 15:13 UTC, MinuraPunchihewa requested changes
I don't think this is the optimal way to go about doing this for the following reasons:
1. It does not really solve the issue. The message is still displayed in the Error column (as shown in the screenshot), it just adds 'Info' to the front.
2. Checking this condition against the error message is not very robust. I think it would be better if we can maybe add an extra (optional) attribute to the `HandlerStatusResponse` class and act on that.

2024-10-23 06:46 UTC, ea-rus commented on mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
> +                auth_url = error_message.split("AUTHORIZATION_REQUIRED:")[1].strip()
why don't use different exception types instead of parsing message?

2024-10-23 06:46 UTC, ea-rus commented on mindsdb/api/executor/command_executor.py
> +            if "Authorization required" in error_msg or "Authorisation required" in error_msg:
parsing error messages is not reliable is better to look at exception type

2024-11-05 11:38 UTC, closed without merging