Updated crate_handler to be able to connect with crate database hosted on cloud
mindsdb/mindsdb pull request #9938
Opened 2024-10-18 14:01 UTC by Sekhar-Kumar-Dash

## Description

Updated crate_handler to be able to connect with crate database hosted on cloud

Fixes #9937

## Type of change
- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.
![{A321983E-F600-4CD3-8802-3C2EE929E880}](https://github.com/user-attachments/assets/362ea9f0-0a65-4df7-be10-33fd7ec4fbf0)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

2024-10-21 05:50 UTC, MinuraPunchihewa requested changes

2024-10-22 10:13 UTC, Sekhar-Kumar-Dash commented on mindsdb/integrations/handlers/crate_handler/crate_handler.py
i am working on it

2024-10-22 14:54 UTC, Sekhar-Kumar-Dash commented on mindsdb/integrations/handlers/crate_handler/crate_handler.py
@MinuraPunchihewa  i have made the required changes please take a look

2024-10-22 15:02 UTC, MinuraPunchihewa approved these changes

2024-10-23 11:38 UTC, ZoranPandovski requested changes
Please fix flake8 warnings https://github.com/mindsdb/mindsdb/actions/runs/11462839418/job/31944430591?pr=9938#step:6:115

2024-10-24 11:22 UTC, ZoranPandovski approved these changes

2024-10-24 11:22 UTC, merged